In [3]:
#dataset, karena ga tau cara import csv lewat colab google
dataset=[[1,1.041958,411.989685,0.295574,0.910293,0.056183,2235,0.788595,2145,0.532083,0.391224,0.785876,0.732821,2.337866,1.517679,104.16246,13.242218,0.316153,0.363583,23.006937,83.384605,0.077348,28320,67.830696,8.136516,20.572479,0.750944,61.313919,125.540268,22333],
[1,0.867508,423.807465,0.276264,0.819063,0.022913,4125,0.634938,4755,1.053555,0.39304,0.577366,0.744377,3.669929,1.42815,63.401608,22.188545,0.30624,0.359131,38.329887,50.648056,0.027157,48863,71.498077,9.076974,32.688419,0.708191,26.69227,71.531929,31025],
[1,2.514205,373.516144,0.274679,0.8254,0.007296,7965,0.680373,3168,1.002722,0.4462,0.599164,0.703877,6.926087,1.648434,65.156616,18.550638,0.314406,0.293116,35.190125,57.636204,0.067783,54135,69.066055,11.77747,28.637329,0.753462,31.138128,127.077431,36832],
[1,2.064885,411.183746,0.263279,0.815429,0.006674,8115,0.680018,3930,1.047981,0.469368,0.577987,0.695137,7.431319,1.662973,66.084785,18.314508,0.308895,0.267211,34.919922,61.574825,0.041846,51431,66.335373,13.302699,28.886127,0.575643,34.198906,126.954521,34974],
[1,2.439204,449.707581,0.228109,0.758283,0.004056,9930,0.551612,4071,1.334461,0.35765,0.475496,0.758286,8.316583,1.343836,66.808174,25.652452,0.316021,0.394241,48.614101,49.471413,0.043751,57700,76.921638,11.433691,39.452927,0.836773,27.163689,147.499649,31828],
[1,2.581576,315.389404,0.242267,0.77745,0.006117,6978,0.530342,2703,1.304549,0.332632,0.473613,0.786628,6.533708,1.230935,53.952385,22.601267,0.318026,0.428663,44.436192,37.614346,0.076865,44690,69.807327,8.621966,34.568325,0.31098,19.595343,90.372208,23701],
[1,1.166911,481.051636,0.242138,0.765215,0.007803,7173,0.522915,6147,1.349632,0.330642,0.464251,0.779305,5.766077,1.261649,63.488342,29.484987,0.296766,0.434828,51.921135,44.267654,0.020318,61094,79.742218,9.485422,42.271564,0.653611,24.819304,99.338615,31947],
[1,1.000627,429.702301,0.273889,0.797555,0.015744,4785,0.566671,4782,1.185297,0.343561,0.523086,0.779894,4.139273,1.265952,66.707657,26.333082,0.299583,0.420945,46.387035,47.974838,0.027818,50622,78.260277,10.557991,36.513149,0.273815,25.246431,79.043915,28686],
[1,1.757782,385.725739,0.268239,0.797553,0.012035,5421,0.630573,3084,1.174511,0.438259,0.527767,0.713008,5.346154,1.593338,60.061481,21.753721,0.314506,0.302863,41.579742,52.133106,0.058972,44634,71.431885,9.860604,33.718357,0.360196,26.14142,99.393921,28145],
[1,1.874552,343.112488,0.272751,0.782707,0.008499,6276,0.540345,3348,1.291075,0.348072,0.473379,0.777035,5.66426,1.288087,58.653553,25.858793,0.317081,0.410599,47.972572,42.420563,0.05527,49300,74.5793,9.376661,39.881699,0.729719,24.212234,98.397949,26639],
[1,1.423712,525.832275,0.253547,0.782831,0.00429,12681,0.640405,8907,1.215461,0.457309,0.522469,0.696312,9.149351,1.658149,68.033195,23.991095,0.300926,0.280668,43.0205,61.583015,0.013579,85727,73.897148,12.654294,34.626331,0.597897,32.101109,132.483994,54900],
[1,1.87395,328.263489,0.27089,0.828853,0.012895,6021,0.687044,3213,1.002751,0.469484,0.595673,0.705,5.347247,1.641759,60.322857,17.99827,0.308603,0.271182,33.736469,55.726059,0.065909,54145,65.57711,11.053498,26.951323,0.78339,27.657429,84.275307,37200],
[1,1.591575,327.084381,0.268333,0.841546,0.0163,5214,0.70916,3276,0.926804,0.46651,0.631739,0.69286,4.74,1.6743,62.240177,17.185001,0.314349,0.274557,30.763126,56.97768,0.058223,49725,64.233215,9.179589,25.228035,0.810134,26.496277,82.86161,35263],
[1,2.153398,313.615784,0.266154,0.806441,0.007045,6654,0.601765,3090,1.144604,0.376367,0.537078,0.764054,6.472763,1.352859,51.220791,20.363977,0.315967,0.372806,36.572079,39.230465,0.054286,41247,64.83786,9.223431,29.682877,0.462149,20.848322,79.882202,24821],
[1,1.183829,406.449707,0.280247,0.790041,0.019092,4656,0.639273,3933,1.212062,0.476181,0.513252,0.687378,4.409091,1.713084,65.864754,25.382971,0.317837,0.264776,45.476471,61.923027,0.041855,51521,75.770134,10.288476,37.738964,0.613283,31.929028,94.894691,32936],
[1,3.045509,367.868591,0.24477,0.780308,0.005868,7629,0.599145,2505,1.293738,0.426311,0.482346,0.723186,7.553465,1.543422,59.778351,21.099335,0.324527,0.311078,42.935783,50.559368,0.090844,45363,69.553505,11.729836,32.602047,0.781089,26.309126,126.98362,27179],
[1,0.868613,344.486908,0.297397,0.80311,0.034311,3213,0.612242,3699,1.177047,0.414168,0.526408,0.741185,3.077586,1.4379,59.083771,24.588932,0.31769,0.335748,42.416752,49.230412,0.042283,46039,72.06443,9.812569,34.771881,0.494815,24.858427,49.159668,28187],
[1,1.663848,344.638031,0.272937,0.837263,0.010225,7083,0.698272,4257,0.950654,0.457917,0.619321,0.701365,5.922241,1.648766,61.436592,16.67931,0.311488,0.282615,31.101341,55.474106,0.040538,58460,63.519474,10.14583,26.158899,0.462754,29.176376,95.600388,40821],
[1,1.299946,484.311188,0.245882,0.748368,0.0074,7242,0.521135,5571,1.446074,0.354912,0.4303,0.768235,6.137288,1.299548,63.979141,32.552345,0.306658,0.402447,55.100948,47.120956,0.023995,59261,80.275597,10.352946,47.583973,0.382232,27.271307,99.85083,30883],
[1,0.604963,443.180634,0.27285,0.767063,0.026404,3657,0.53783,6045,1.356699,0.359795,0.45727,0.768869,3.27102,1.314404,58.047604,29.810575,0.290421,0.400998,50.734032,42.992996,0.017967,52247,76.620857,6.81717,42.974201,0.247737,20.757835,59.627033,28100],
[1,1.355569,435.08786,0.275053,0.831467,0.010022,6645,0.670596,4902,0.981286,0.420562,0.602618,0.722802,5.738342,1.548323,62.431053,17.797129,0.306085,0.323487,32.941044,52.31213,0.027463,52516,65.079956,10.420287,27.385105,0.586175,28.520277,101.883423,35217],
[1,1.469072,365.63916,0.284168,0.834321,0.012288,5985,0.691407,4074,0.977506,0.461555,0.605784,0.705936,5.421196,1.652247,57.861412,17.307076,0.313383,0.279023,32.356148,52.361813,0.038355,50659,64.247421,9.618235,26.151211,0.774432,26.920105,88.827377,35026],
[1,2.97332,331.332642,0.241191,0.786225,0.003889,9027,0.512321,3036,1.257538,0.295795,0.490874,0.797798,7.728596,1.151711,57.068806,23.015001,0.318886,0.476626,43.983589,36.609653,0.067108,49223,71.078712,8.470799,36.436619,0.644784,21.463879,122.1147,25218],
[1,3.107852,362.650787,0.25613,0.810095,0.0054,9855,0.662707,3171,1.08017,0.462363,0.557663,0.696978,8.198835,1.643722,70.940239,19.423319,0.320502,0.27411,38.55278,65.209259,0.078698,62972,70.084961,14.776563,29.049969,0.628823,35.1353,143.390717,41732],
[1,2.447596,322.056091,0.25744,0.808634,0.010582,5955,0.656762,2433,1.092538,0.45764,0.555266,0.698993,5.82681,1.633766,67.048485,20.082453,0.325187,0.281108,38.585411,60.91338,0.096521,45467,69.54422,11.828444,29.301947,0.882411,30.31744,114.329361,29861],
[1,1.48506,321.116669,0.263526,0.812676,0.017937,4473,0.624915,3012,1.101562,0.400735,0.55607,0.745879,4.188202,1.433175,61.077282,21.30411,0.316057,0.348241,39.269436,49.175938,0.0633,45699,70.568481,10.13624,31.035839,0.581972,24.111277,84.243942,28558],
[1,1.727761,315.770508,0.272726,0.710595,0.005156,8682,0.378176,5025,1.688146,0.256911,0.317129,0.828577,6.255043,0.995836,59.589523,35.983669,0.31986,0.538398,66.994919,34.937733,0.0407,81782,78.955818,7.782355,48.305565,0.358794,19.4296,85.096565,30928],
[1,1.007035,412.668671,0.275885,0.76822,0.011067,5583,0.498122,5544,1.348064,0.303634,0.461062,0.802932,4.637043,1.136022,55.512218,29.745745,0.304677,0.473767,50.423473,36.368587,0.02253,55107,76.926392,8.043703,43.368145,0.596476,20.749704,66.752525,27450],
[1,0.952655,388.664093,0.258231,0.794497,0.01788,4467,0.564489,4689,1.208116,0.347095,0.516769,0.768578,3.90472,1.3144,64.331688,27.118477,0.311959,0.416743,46.046177,46.589565,0.028746,50295,77.197868,6.973385,39.53933,0.647296,22.409678,67.37072,28391],
[1,1.400424,312.048431,0.267715,0.81148,0.018569,3966,0.627155,2832,1.111899,0.408632,0.55174,0.740191,4.157233,1.448616,58.267696,20.802584,0.314912,0.338521,37.651176,47.908737,0.058068,37061,67.55088,10.22013,29.784599,0.371475,25.003973,72.669693,23243],
[1,1.562296,398.511627,0.264845,0.8229,0.008676,7185,0.634956,4599,1.025353,0.373324,0.593702,0.74956,5.813107,1.408536,64.400383,20.252523,0.303056,0.380814,36.464481,49.222588,0.03335,56133,70.463043,9.250178,29.876959,0.694004,25.961025,94.173897,35642],
[1,1.313368,342.110504,0.279186,0.846008,0.020835,4539,0.721202,3456,0.889582,0.477374,0.642905,0.690998,4.242056,1.688934,65.792824,16.722916,0.311002,0.263712,30.27767,62.292038,0.049832,47364,64.32283,10.420509,23.163704,0.577123,32.087273,78.573219,34159],
[1,0.813293,409.713806,0.26557,0.815657,0.020611,4038,0.581353,4965,1.087218,0.326656,0.564745,0.787849,3.52356,1.235054,60.31419,24.414928,0.296786,0.444371,39.830612,41.49641,0.023451,46003,72.818474,7.011298,34.313221,0.697139,21.586073,59.711632,26744],
[1,2.46988,392.801819,0.260568,0.812078,0.008125,7380,0.689679,2988,1.050909,0.494815,0.576613,0.666862,6.910112,1.778166,67.634727,18.386578,0.319558,0.241466,35.709278,66.263451,0.071867,51060,67.64978,11.861511,29.485962,0.774254,35.37344,135.020248,35215],
[1,2.326531,486.175598,0.250209,0.747404,0.004988,7866,0.540757,3381,1.403837,0.368959,0.44208,0.753433,7.622093,1.366803,66.551895,26.631989,0.315159,0.378334,51.783199,50.493156,0.049926,45416,77.437294,11.956417,41.472214,0.808804,28.226357,161.017487,24559],
[1,1.526733,369.436157,0.285074,0.774109,0.014746,4626,0.568045,3030,1.298846,0.384007,0.479389,0.746367,4.517578,1.413754,58.815289,25.19062,0.320125,0.366938,46.521717,45.863255,0.060507,44206,73.333389,8.760139,36.843788,0.297743,23.42441,88.012177,25111],
[1,2.350978,355.546356,0.273269,0.815114,0.009917,6129,0.662828,2607,1.060411,0.445388,0.573985,0.709255,5.938953,1.59881,65.328476,19.103577,0.323489,0.294412,37.666992,57.709782,0.082695,44725,70.379166,11.791226,29.74626,0.750414,30.254087,116.040253,29645],
[1,1.52745,430.262573,0.265592,0.829226,0.010098,6594,0.679112,4317,0.968228,0.424221,0.61288,0.721607,5.743902,1.569887,63.807285,18.033606,0.293459,0.318913,33.319626,53.763103,0.034693,51451,67.198006,9.77624,27.01548,0.910415,28.153099,112.405159,34941],
[1,0.924298,486.48996,0.269519,0.842501,0.007916,6813,0.578543,7371,0.939914,0.272686,0.617041,0.822122,5.200763,1.041788,57.936794,20.321144,0.261796,0.517255,33.622459,35.289276,0.011689,50539,68.308342,7.857917,28.550669,0.325813,20.667152,74.533798,29239],
[1,2.097307,385.319977,0.262312,0.790565,0.007638,7242,0.625807,3453,1.182543,0.42787,0.527968,0.718708,6.631868,1.571759,64.379028,21.903347,0.314916,0.312806,40.994442,55.027718,0.053687,50939,70.972343,11.096008,32.057743,0.574257,29.552601,120.576416,31878],
[1,1.756039,290.921173,0.29011,0.85539,0.019216,4362,0.755544,2484,0.860586,0.545768,0.654455,0.651777,4.720779,1.851598,57.460918,13.608831,0.312929,0.196843,24.872036,61.701305,0.07843,38510,55.086273,9.412346,19.937069,0.68483,27.870367,79.851074,29096],
[1,1.303431,511.498016,0.252406,0.80969,0.004867,10941,0.635894,8394,1.099305,0.405821,0.560028,0.729631,8.068584,1.497099,65.951401,21.950966,0.273246,0.339341,38.115086,53.80022,0.013003,72910,70.023613,10.990617,30.090752,0.703403,26.756006,109.74424,46363],
[1,0.679677,489.694916,0.246656,0.826411,0.007864,7836,0.727925,11529,1.012069,0.411896,0.599376,0.725335,6.412438,1.567297,66.940697,23.520624,0.281441,0.333404,35.923504,55.393589,0.004991,52787,70.688354,13.650705,32.953842,0.457658,33.006355,145.667038,38425],
[2,1.135215,330.583557,0.282091,0.782818,0.023029,4584,0.572295,4038,1.274188,0.392099,0.484219,0.789315,3.655502,1.294388,86.519043,22.940983,0.327345,0.361509,57.455513,69.265465,0.051857,67287,89.591751,2.407056,42.857376,0.349206,36.146603,70.23159,38508],
[2,2.055172,375.799042,0.22169,0.730394,0.004562,8940,0.516797,4350,1.518158,0.363553,0.409616,0.79304,7.911504,1.217753,85.103142,21.13567,0.314056,0.387401,65.19133,64.045326,0.037282,56140,91.454796,1.680981,42.529499,0.367204,26.763433,83.940338,29013],
[2,0.70524,470.679718,0.305552,0.738174,0.067047,1938,0.497085,2748,1.534279,0.355276,0.396197,0.800002,2.04,1.219018,87.946037,36.105526,0.321506,0.409243,67.726204,65.14946,0.067084,40313,90.797142,3.112457,53.536701,0.342608,36.457237,50.381756,20039],
[2,0.956179,481.358154,0.287827,0.71775,0.011474,6546,0.452397,6846,1.644044,0.332636,0.341445,0.778239,4.771137,1.299293,66.800186,45.918255,0.306336,0.43646,68.05442,46.909763,0.023189,86486,83.390663,12.466963,56.392803,0.347903,27.182251,103.626511,39126],
[2,0.541314,498.152679,0.269606,0.673924,0.019905,4599,0.356746,8496,1.91034,0.26657,0.25952,0.822055,3.234177,1.06001,61.945225,60.982025,0.286563,0.530903,84.417953,37.198116,0.016349,93910,88.387001,8.737281,72.511932,0.135595,21.756313,69.991188,33502],
[2,0.828035,443.869598,0.258104,0.654107,0.014157,5157,0.359558,6228,2.006794,0.27776,0.243358,0.820031,3.924658,1.065522,57.993977,54.564632,0.318343,0.512654,81.920738,35.777,0.026997,83330,83.789459,6.533957,67.832291,0.34067,18.904015,54.972889,29962],
[2,1.071787,334.4729,0.255894,0.708232,0.019573,4479,0.430038,4179,1.725251,0.322034,0.317351,0.784792,3.594703,1.236571,62.351883,46.175358,0.321242,0.451091,69.880638,42.80368,0.052284,72661,81.707207,8.529084,57.433167,0.178253,22.414656,70.514519,31247],
[3,0.744318,270.726898,0.321244,0.900812,0.116319,1965,0.769319,2640,0.630257,0.451047,0.735512,0.694132,1.745115,1.659464,84.861626,18.222136,0.326695,0.296704,24.949659,76.718384,0.083765,46458,63.182503,9.965598,19.070709,0.697649,43.281803,61.238342,35741],
[3,0.492972,558.470642,0.313782,0.824798,0.075986,2841,0.68505,5763,1.097466,0.555423,0.539552,0.636032,2.395447,2.020801,96.225731,37.851028,0.309017,0.193067,51.515762,107.299431,0.026956,71243,88.674164,9.517924,43.858917,0.52849,65.515663,97.524025,48805],
[3,0.607306,459.905731,0.32355,0.854873,0.101592,2394,0.707908,3942,0.906225,0.5047,0.614556,0.666148,1.975248,1.850322,99.497475,31.915125,0.324368,0.240999,44.25832,100.251282,0.05293,65452,86.512703,11.05491,35.942574,0.621074,67.947693,95.603256,46334],
[3,0.967021,400.137939,0.316635,0.905363,0.076005,2727,0.813905,2820,0.570009,0.511637,0.766525,0.658664,2.299325,1.894151,102.931335,17.522398,0.327717,0.233562,25.210011,105.191238,0.087325,55262,69.326256,13.114197,20.841053,0.680029,72.698692,119.727928,44978],
[3,0.569378,452.396698,0.32219,0.855087,0.120132,2142,0.745686,3762,0.887646,0.57115,0.635302,0.617588,1.92973,2.033218,96.716827,26.851919,0.328888,0.179559,40.15015,111.346268,0.052228,58821,81.946663,10.779142,32.184204,0.608521,67.797684,98.128052,43862],
[3,0.581555,480.976471,0.322358,0.874581,0.103731,2535,0.776741,4359,0.775225,0.583564,0.679714,0.601545,2.10199,2.129653,101.945679,24.885523,0.326118,0.169503,35.588448,120.461418,0.045166,68293,79.431396,15.824632,29.223246,0.839316,84.509109,106.47345,53046],
[3,0.687993,467.506256,0.323359,0.870745,0.097848,2355,0.732317,3423,0.811681,0.495582,0.657844,0.653432,1.992386,1.855368,106.004013,29.34178,0.326914,0.249612,40.361988,104.896896,0.063244,58969,85.964714,10.717024,34.059883,0.502366,72.13044,117.097748,43184],
[3,0.501522,630.651855,0.303311,0.839113,0.10118,1977,0.692364,3942,1.029078,0.530763,0.567982,0.678413,2.029774,1.830717,99.543968,36.968243,0.3258,0.215333,50.195068,105.657494,0.036757,45453,90.747917,8.54864,42.845139,0.59945,66.731918,119.468193,31470],
[3,0.542585,447.340485,0.325697,0.820002,0.076563,2733,0.640678,5037,1.138979,0.477744,0.524861,0.740414,2.211165,1.607404,95.611359,37.388626,0.309277,0.268725,53.19854,91.256638,0.035181,71031,88.404266,5.331003,45.750065,0.633972,55.22641,86.843552,45508],
[3,0.551519,428.925018,0.327398,0.83101,0.096331,2505,0.661364,4542,1.048758,0.472724,0.563758,0.697387,1.963166,1.753905,103.287117,35.405113,0.313883,0.273605,51.036655,97.668114,0.044304,72733,90.609901,10.442486,41.980915,0.703111,63.631798,87.933441,48103],
[3,0.695053,363.205963,0.312551,0.834493,0.097639,2571,0.652468,3699,1.053292,0.472593,0.549415,0.683358,1.947727,1.746175,97.404175,36.466953,0.326953,0.273845,51.942039,92.052132,0.072293,78715,89.90168,10.775616,43.074028,0.50173,60.887253,85.913132,51359],
[3,0.688623,240.389542,0.318325,0.867205,0.088198,2415,0.698974,3507,0.835027,0.448346,0.639547,0.712328,1.989292,1.607255,80.124588,23.140207,0.325621,0.299896,33.477921,72.035912,0.059836,58563,68.805244,8.059134,25.458719,0.583268,40.74057,58.705326,40934],
[3,0.432087,442.165344,0.321313,0.79131,0.090224,2739,0.572169,6339,1.303131,0.43616,0.444136,0.701881,1.94808,1.640462,97.844383,47.921867,0.312279,0.313934,65.702736,85.935242,0.02944,94140,94.890984,8.932111,57.2099,0.653397,59.909641,78.150742,53864],
[3,0.569095,409.467926,0.323682,0.853145,0.104591,2508,0.693096,4407,0.945362,0.49879,0.596899,0.654449,1.935185,1.863387,103.030739,34.408249,0.326013,0.247389,47.315636,102.623734,0.048873,75535,89.114532,12.18086,40.468418,0.625609,70.891304,85.550232,52353],
[3,0.543933,388.463837,0.329531,0.857052,0.119522,2340,0.683429,4302,0.90064,0.450581,0.616166,0.713684,1.720588,1.628586,102.879471,30.806618,0.326873,0.298272,44.726685,93.066338,0.051742,76204,87.176117,7.322649,38.181305,0.83668,62.155281,78.941437,52080],
[3,0.542298,473.233734,0.315388,0.837229,0.095247,2577,0.646846,4752,1.027627,0.45238,0.556191,0.703451,1.928892,1.672642,102.977066,39.060162,0.325871,0.295693,53.603333,93.423073,0.043304,77816,93.745514,9.984668,45.174274,0.550532,64.90049,94.750504,50335],
[3,0.483755,470.305145,0.327178,0.810634,0.108955,2412,0.655287,4986,1.137241,0.518231,0.518795,0.63917,1.932692,1.925841,103.523827,41.46339,0.328662,0.227936,58.062782,107.221008,0.03891,76977,95.052094,13.978682,49.907887,0.608128,75.977028,102.744789,50442],
[3,0.496685,433.772919,0.328555,0.817102,0.100261,2472,0.620522,4977,1.157399,0.457742,0.509356,0.709709,1.892802,1.665849,102.860748,42.311054,0.327666,0.290175,59.563816,94.298164,0.03986,78571,95.700478,7.887853,50.083305,0.664337,62.855652,82.586876,48755],
[3,0.48481,467.324615,0.327254,0.868441,0.11337,2298,0.732109,4740,0.831778,0.505684,0.653155,0.671072,1.871336,1.842622,101.180397,28.878477,0.329485,0.240354,39.644424,102.16069,0.036397,65075,83.50576,9.813635,33.834057,0.891738,65.662697,88.166832,47642],
[3,0.376422,450.418671,0.314509,0.815329,0.096428,2481,0.56555,6591,1.199101,0.391572,0.479329,0.729698,1.784892,1.5318,100.804398,47.222584,0.326822,0.36607,63.319588,80.768356,0.024159,83517,97.001068,10.462263,55.779869,0.465983,57.655334,78.83609,47233],
[3,0.469194,433.209137,0.319152,0.813084,0.091592,2673,0.617641,5697,1.174235,0.462709,0.498886,0.693768,1.991803,1.70418,103.515572,43.003464,0.329917,0.284531,60.68903,95.942719,0.032646,84316,95.982964,9.02614,51.486362,0.529734,65.239998,94.273468,52077],
[3,0.835443,460.888977,0.302567,0.869913,0.085113,1782,0.680676,2133,0.819559,0.381686,0.660656,0.73258,1.87579,1.520956,101.38401,27.3211,0.324182,0.376206,39.001385,79.531677,0.087275,31598,83.916161,12.684348,34.613167,0.446513,49.722149,113.366585,21508],
[3,0.370672,930.855286,0.302856,0.858993,0.063801,2184,0.621778,5892,0.88523,0.34505,0.602306,0.7513,2.056497,1.397018,98.012779,36.343285,0.296279,0.422014,45.11507,71.020729,0.014098,38948,88.252403,13.792802,43.376511,0.698614,44.957912,125.022942,24217],
[3,0.60587,477.014435,0.312677,0.882202,0.094517,1734,0.650698,2862,0.757679,0.322224,0.67093,0.780361,1.632768,1.292293,94.364639,27.707212,0.321413,0.453645,36.97776,64.972176,0.05332,34755,81.297531,8.961672,34.309158,0.488204,49.676281,102.700249,22615],
[3,0.419838,690.716431,0.3108,0.845556,0.071646,2019,0.54837,4809,0.968173,0.307384,0.542478,0.780974,1.835455,1.271365,96.514488,44.574471,0.315258,0.473747,54.642132,64.1679,0.023029,42382,95.082954,8.652092,53.769459,0.421192,50.538403,118.360352,23241],
[3,0.594937,735.181641,0.315173,0.877276,0.058757,2397,0.724847,4029,0.770493,0.448468,0.669081,0.676046,2.445918,1.750886,105.147728,27.135633,0.311404,0.297662,37.232491,94.65712,0.028692,37063,82.49675,18.119324,34.090595,0.587406,79.392197,165.301682,26865],
[3,0.902941,540.227966,0.319685,0.922232,0.088573,1842,0.842611,2040,0.45717,0.470296,0.816022,0.675742,2.037611,1.794264,105.470375,12.818372,0.32404,0.274413,19.064522,99.214684,0.085702,28382,61.847256,12.712965,17.640303,0.760735,80.388176,150.085968,23915],
[3,0.864222,693.336365,0.308765,0.888753,0.048185,2616,0.766116,3027,0.668448,0.451925,0.723072,0.672054,2.713693,1.789244,103.600311,19.8703,0.321027,0.292388,29.602291,93.909515,0.046975,34252,74.661301,16.074003,27.850082,0.699294,78.959061,204.566513,26241],
[3,1.052437,725.820007,0.273755,0.871146,0.014319,5118,0.656216,4863,0.793016,0.332776,0.660306,0.757553,4.27212,1.357245,98.945274,24.327057,0.303549,0.434922,37.259506,69.794937,0.02417,45485,81.633347,17.217228,34.495853,0.461197,59.401096,238.874634,29848],
[3,0.627119,770.766052,0.287638,0.888235,0.037562,2664,0.663819,4248,0.712247,0.310622,0.690641,0.778367,2.546845,1.269667,98.29966,25.349367,0.302967,0.467539,35.065411,65.891243,0.022253,31956,81.552109,15.242239,33.186462,0.626706,55.145184,171.627579,21213],
[3,0.67444,635.315002,0.315128,0.911311,0.069769,2169,0.767175,3216,0.5446,0.365504,0.773999,0.729842,2.023321,1.475767,103.372116,17.939129,0.32024,0.395999,24.333473,78.355934,0.041367,34047,69.897926,12.644011,22.776808,0.711248,65.134209,146.717667,26120],
[3,0.856155,441.822876,0.310785,0.848202,0.085938,1857,0.616662,2169,0.936068,0.351749,0.598056,0.754337,1.792471,1.399538,95.665031,32.826504,0.324063,0.414155,47.055588,70.353836,0.102151,38243,89.93222,10.850667,42.84063,0.502776,55.814377,116.478844,23583],
[3,0.625325,577.17157,0.320448,0.894781,0.082832,2163,0.761626,3459,0.644035,0.436072,0.729624,0.68289,2.032895,1.704712,107.387741,20.995377,0.321556,0.31234,29.72838,94.317772,0.042527,40491,75.066345,18.366091,26.779808,0.510963,77.909599,135.399628,30839],
[3,0.597234,457.146118,0.29662,0.812868,0.08444,2073,0.572301,3471,1.218377,0.411404,0.467847,0.756024,1.95566,1.471814,95.752251,50.12915,0.326532,0.341337,63.576958,79.868454,0.052628,50456,95.758873,5.306487,54.087906,0.281189,44.830673,82.24482,28876],
[3,1.094755,413.665894,0.310656,0.744731,0.030877,3882,0.517374,3546,1.493636,0.386572,0.397038,0.759468,3.135703,1.411595,89.342361,44.92688,0.327868,0.369108,73.976074,70.665421,0.071527,71571,98.947357,5.940389,59.63699,0.713236,39.873158,108.743645,37029],
[3,1.098453,331.152832,0.324258,0.929114,0.062243,2343,0.870948,2133,0.457433,0.567472,0.813166,0.66211,2.6625,1.999278,76.6511,12.013774,0.313425,0.181039,16.605476,86.312691,0.086231,31220,54.583954,22.466734,13.532495,0.560573,50.250355,165.270218,27191],
[3,0.767232,507.435333,0.321628,0.850156,0.08471,2037,0.747049,2655,0.881086,0.540346,0.64949,0.687102,2.223799,1.761903,87.142693,22.343147,0.31524,0.205205,35.540054,93.920059,0.066748,37442,75.874115,6.648546,27.528503,0.387734,47.552441,83.255829,27971],
[4,0.269434,1139.956055,0.324231,0.868031,0.109746,1986,0.674143,7371,0.8771,0.422661,0.612431,0.699962,1.739054,1.702211,105.747704,38.167599,0.315805,0.32834,45.294708,90.343224,0.011818,51096,90.171852,18.000454,39.755711,0.621534,70.200874,155.213165,34446],
[4,0.299598,1130.660034,0.323365,0.896637,0.100593,2238,0.757563,7470,0.670937,0.466155,0.702585,0.661753,1.906303,1.862272,107.991264,28.747925,0.312314,0.280112,32.886246,100.768921,0.011919,52925,79.704079,22.906651,30.537148,0.783162,84.935066,170.199951,40094],
[4,0.747301,973.26947,0.260012,0.879558,0.01481,5607,0.730184,7503,0.712085,0.389846,0.705893,0.736669,4.536408,1.501628,89.644875,23.914509,0.295137,0.362438,29.720791,71.511719,0.011327,50742,72.625443,31.359249,26.765888,0.67701,54.117634,258.893585,37051],
[4,0.319894,820.732544,0.295594,0.795489,0.037476,3975,0.537396,12426,1.266251,0.374092,0.443587,0.752643,2.799296,1.463614,86.055237,54.878662,0.286504,0.386819,64.813118,66.380684,0.007136,87684,94.342804,23.831877,60.581924,0.759848,48.521122,119.523422,47121],
[4,0.28309,879.654663,0.287797,0.852035,0.042289,3375,0.568488,11922,0.960357,0.306749,0.569681,0.790654,2.386846,1.245784,80.469864,41.491295,0.25507,0.47497,48.152519,53.400352,0.005961,67428,87.691109,16.265465,45.340366,0.50523,35.630993,120.898399,38332],
[4,0.155433,1590.760376,0.312669,0.845476,0.102087,1944,0.556117,12507,1.055017,0.337782,0.508432,0.761315,1.61194,1.393899,99.531052,53.300407,0.299419,0.434052,59.884674,70.993034,0.004435,55206,99.913284,12.889251,56.207062,0.460195,56.36113,123.714516,30701],
[4,0.346681,653.877441,0.314887,0.932805,0.10658,1974,0.827881,5694,0.438086,0.394794,0.823877,0.740025,1.692967,1.49303,63.525322,13.617737,0.301369,0.362074,15.32116,50.864773,0.015473,39920,52.596073,12.918459,14.0485,0.413638,29.5415,59.893589,33049],
[4,0.310947,678.209106,0.31153,0.876756,0.090186,1764,0.641171,5673,0.783106,0.308619,0.665243,0.79746,1.639405,1.196978,55.272877,27.430025,0.299737,0.47273,31.733931,36.399841,0.0136,34830,70.381721,8.675917,28.711655,0.475577,17.621675,61.709286,22332],
[4,0.243243,837.626953,0.304685,0.791226,0.066621,2592,0.584803,10656,1.292815,0.425442,0.467708,0.723158,2.238342,1.599433,66.480644,44.770653,0.274203,0.324954,53.483372,56.421249,0.00674,60906,82.458328,12.821046,50.033264,0.62307,31.740242,88.724365,35618],
[4,0.169778,1860.824707,0.301963,0.818936,0.038089,2919,0.459104,17193,1.263854,0.288369,0.406248,0.809649,2.4325,1.155193,70.239037,70.872803,0.248387,0.500144,72.662277,44.536449,0.002391,56253,103.930191,16.187351,66.885391,0.698431,26.5781,100.004021,25826],
[4,0.385029,864.035217,0.289893,0.653918,0.015676,5586,0.36678,14508,2.166895,0.338281,0.161421,0.780411,4.101322,1.321062,63.005486,96.813339,0.311105,0.429337,109.042282,44.601662,0.006336,106129,93.705009,13.181559,94.491776,0.330824,23.907475,138.938568,38926],
[4,0.217357,1319.26001,0.303087,0.778453,0.094863,1668,0.533531,7674,1.490215,0.47398,0.325132,0.705138,1.971631,1.656006,56.942928,84.686111,0.302958,0.270847,85.536018,52.943626,0.0084,39366,105.46479,16.300438,77.540756,0.531095,22.465923,81.539032,21003],
[5,0.683213,263.978943,0.328453,0.926394,0.107245,2271,0.858796,3324,0.448103,0.521641,0.823833,0.667397,1.954389,1.824027,85.785011,10.313364,0.329,0.22467,15.250966,89.362854,0.058291,51252,49.90202,8.959669,11.883062,0.913071,51.496754,55.327209,44015],
[5,0.406769,627.410645,0.329646,0.858415,0.1295,1911,0.751583,4698,0.840602,0.531914,0.665651,0.708912,1.796053,1.718875,99.329094,25.35428,0.325126,0.215546,36.288799,105.722,0.028509,50073,78.816322,4.617664,30.503265,0.890755,59.309731,70.806213,37634],
[5,0.417902,531.534729,0.329325,0.822454,0.114932,2115,0.637467,5061,1.128912,0.471717,0.524314,0.694925,1.795416,1.738842,103.057236,42.872906,0.325215,0.274819,56.772869,97.230316,0.031487,64179,94.071281,8.37551,49.560093,0.887323,65.546135,86.059921,40912],
[5,0.502928,540.908875,0.329328,0.880437,0.12406,2061,0.779751,4098,0.73687,0.546562,0.701352,0.678048,1.860108,1.882535,101.65683,23.186693,0.326902,0.201942,32.5737,111.270119,0.040243,53780,76.418549,8.015314,27.926138,0.86662,69.672089,93.03257,41935],
[5,0.5629,491.800354,0.327665,0.880273,0.114143,2376,0.795106,4221,0.7307,0.585927,0.70758,0.65859,2.006757,1.951941,100.480476,22.546459,0.327299,0.168219,31.932652,119.360893,0.045487,64492,75.929527,7.536599,26.222645,0.921609,73.432175,83.859688,51278],
[5,0.57805,480.039032,0.327371,0.859189,0.101707,2544,0.763616,4401,0.879954,0.623583,0.638667,0.584287,2.193104,2.193614,99.533249,29.395203,0.311449,0.137913,40.775761,127.864014,0.044505,68596,83.610695,14.167119,34.975975,0.745725,87.660645,103.704414,52381],
[5,0.895105,422.12262,0.322733,0.895124,0.06299,2304,0.821012,2574,0.617246,0.547916,0.755953,0.691294,2.612245,1.834486,85.527496,14.686476,0.314911,0.197857,22.178137,93.561073,0.061471,32410,61.020954,8.923091,16.059633,0.76311,42.85693,108.364647,26609],
[5,0.721996,537.461792,0.316223,0.839755,0.067608,2127,0.711488,2946,0.94227,0.485334,0.625717,0.750285,2.373884,1.578399,83.566757,24.951765,0.295653,0.258847,37.701721,80.484917,0.049533,34210,76.602516,5.736257,28.424578,0.847561,35.765648,92.390121,24340],
[5,0.415677,651.145325,0.325619,0.851018,0.123596,1575,0.765139,3789,0.864943,0.585589,0.652522,0.725049,1.925428,1.701977,82.135689,24.584246,0.29571,0.168579,33.039146,96.850784,0.027911,31887,71.19249,4.141969,27.796947,0.617095,36.855679,72.393784,24398],
[5,0.972684,105.798981,0.319374,0.919526,0.054578,2457,0.843679,2526,0.462095,0.50228,0.802184,0.787572,2.688184,1.482916,75.41481,3.882893,0.312753,0.242189,15.652874,74.684448,0.061204,31077,49.107742,0.967088,5.934425,0.907688,30.105268,23.599844,26219],
[5,1.463209,222.504288,0.300245,0.886444,0.02188,3639,0.755843,2487,0.668819,0.422522,0.721366,0.791864,3.879531,1.307542,82.67057,7.194741,0.311253,0.323458,25.826334,70.346619,0.061977,30505,65.10733,1.554041,13.548745,0.631917,29.767107,44.057579,23057],
[5,1.003401,233.915665,0.318997,0.95149,0.096122,1770,0.926682,1764,0.270332,0.606668,0.886646,0.639128,2.223618,1.959369,84.697952,3.75955,0.321534,0.149336,9.116756,104.352043,0.104434,25860,40.726871,8.703552,5.32703,0.666933,51.882004,82.061691,23964],
[5,0.968952,250.787766,0.304229,0.945871,0.058095,2247,0.918289,2319,0.287798,0.570918,0.87775,0.66155,2.767241,1.874113,84.529617,3.813648,0.29941,0.177651,9.562799,96.388672,0.059397,25419,41.470158,7.957882,5.731515,0.682826,46.02084,88.525902,23342],
[5,0.912387,233.066849,0.318785,0.951555,0.08177,1812,0.924252,1986,0.25073,0.526465,0.892595,0.689512,2.248139,1.766507,82.001007,3.14159,0.308127,0.217119,7.944901,85.49379,0.073649,23116,37.513676,7.625105,4.988024,0.584377,42.290943,82.102638,21365],
[5,1.31068,303.44339,0.323107,0.97483,0.057487,2430,0.96696,1854,0.129966,0.563757,0.943203,0.664086,2.761364,1.986281,76.592773,2.021767,0.326313,0.183808,3.466128,85.643143,0.10213,27936,25.487539,22.096815,2.39828,0.560474,49.802486,172.201614,27013],
[5,1.129808,287.741821,0.323751,0.975738,0.090545,2115,0.969528,1872,0.126941,0.597712,0.946512,0.648392,2.274194,2.044901,79.863327,2.06817,0.324851,0.157147,3.516709,96.150375,0.11921,33244,25.600904,15.558694,2.305523,0.741241,53.505192,131.354233,32231],
[5,1.068132,274.074982,0.327014,0.977023,0.111047,1458,0.975692,1365,0.10697,0.58502,0.952309,0.646841,2.030641,1.953036,79.134529,1.608409,0.327566,0.166268,2.622703,92.661446,0.12985,19253,21.600203,12.57194,1.4763,0.672315,40.328838,123.666962,18785],
[5,0.997963,223.813278,0.323685,0.975827,0.127199,1470,0.968818,1473,0.116064,0.544104,0.947561,0.703242,1.832918,1.776092,84.862045,1.592861,0.324103,0.20261,3.306169,91.895844,0.130759,22577,24.788315,7.42005,2.027413,0.706708,43.529728,97.241669,21873],
[5,0.950161,201.837448,0.317126,0.974464,0.109744,1773,0.963162,1866,0.127397,0.521246,0.94387,0.74218,1.931373,1.638346,87.862778,1.863105,0.318451,0.224931,3.743279,91.053886,0.102867,28503,26.332619,5.623927,2.128503,0.679402,37.85437,81.066048,27453],
[5,1.011338,335.649506,0.327321,0.97055,0.122277,1338,0.965632,1323,0.141799,0.588852,0.938154,0.647729,1.944767,1.985378,79.181602,2.548187,0.327666,0.162884,3.833046,93.891258,0.129517,18040,26.313389,12.017747,2.244668,0.922293,42.377312,142.67981,17420],
[5,0.983229,205.282501,0.325831,0.975983,0.128739,1407,0.968853,1431,0.113968,0.517333,0.949387,0.710549,1.776515,1.689753,82.74514,1.629901,0.326364,0.22739,2.932199,85.258293,0.128458,20933,22.568485,7.542816,1.610004,0.753507,39.679184,84.400185,20281],
[5,0.862816,142.204605,0.325102,0.980094,0.105769,2151,0.965752,2493,0.112244,0.5116,0.952773,0.679306,1.900177,1.77851,87.20652,1.737112,0.325306,0.235112,3.35159,89.01236,0.081532,40324,24.683813,12.216198,2.110641,0.43649,56.070034,57.221275,38943],
[5,0.918534,219.370605,0.322266,0.971566,0.120927,1353,0.968125,1473,0.130926,0.602524,0.939176,0.692578,1.97807,1.826274,80.410889,1.68793,0.32247,0.153604,3.492287,98.365051,0.105385,18196,24.599598,5.935664,2.016931,0.941672,42.771282,84.893921,17616],
[5,0.977444,188.022263,0.325953,0.975401,0.125886,1560,0.969845,1596,0.121532,0.585865,0.946684,0.639501,1.911765,1.932698,78.543388,1.472268,0.326247,0.166365,3.013962,93.025017,0.12401,25137,22.293194,11.122537,2.083245,0.869631,53.392292,81.537979,24379],
[5,1.042857,218.5009,0.329355,0.977365,0.117263,1752,0.977877,1680,0.100822,0.64987,0.952345,0.605763,2.085714,2.114847,83.991005,1.259195,0.330043,0.118083,2.650527,113.997932,0.130414,29291,21.756132,10.001928,1.825683,0.708767,68.982666,100.405838,28643],
[5,0.981197,224.019928,0.322013,0.973454,0.113913,1722,0.967324,1755,0.130953,0.595296,0.942256,0.642894,2.025882,1.968002,84.408073,1.874098,0.3179,0.158842,3.679785,101.952515,0.113374,27788,25.719772,9.299154,2.319639,0.72061,57.698696,95.958824,26880],
[5,0.969283,190.995529,0.326469,0.972862,0.12452,1704,0.963273,1758,0.137836,0.602732,0.937831,0.640019,1.949657,1.948761,81.417313,1.938076,0.325924,0.153596,4.064542,99.974236,0.121449,29869,26.525463,9.903763,2.763051,0.906769,60.454605,86.430702,28772],
[5,0.800853,308.117218,0.32699,0.958793,0.125795,1689,0.937956,2109,0.222031,0.571757,0.907095,0.648425,1.889262,1.917869,87.134872,4.189445,0.325142,0.178447,7.007568,100.381569,0.086018,30446,35.382221,9.82399,5.079826,0.610427,60.901413,95.023651,28557],
[5,0.96325,254.926514,0.32641,0.959402,0.128206,1494,0.934773,1551,0.221998,0.54468,0.908327,0.696965,1.826406,1.743678,83.947922,4.11371,0.326998,0.20257,6.723522,91.499763,0.127257,24361,33.855568,6.661261,4.59192,0.753847,48.788078,82.843185,22772],
[5,0.977586,280.812714,0.326137,0.962387,0.121837,1701,0.947001,1740,0.205217,0.618452,0.914558,0.639335,1.996479,2.046475,87.467552,3.712324,0.326273,0.141264,6.458003,110.997131,0.122953,29623,34.152641,9.705358,4.618871,0.836083,64.471382,99.546501,28053],
[5,0.920477,314.596588,0.327141,0.963542,0.132143,1389,0.949546,1509,0.182599,0.556415,0.922366,0.70534,1.813316,1.715092,90.085587,3.140036,0.325428,0.192324,5.54613,100.54213,0.117911,21366,31.811489,4.529099,4.035489,0.753145,50.581482,101.44239,20288],
[5,0.936283,299.587799,0.322069,0.959963,0.125111,1587,0.94313,1695,0.216164,0.609682,0.909558,0.641476,1.954433,2.024758,88.513504,3.961754,0.322161,0.147628,6.886987,110.334251,0.116289,26587,35.277843,9.594631,4.87517,0.838282,64.712219,101.719917,25075],
[5,0.876623,369.049591,0.324368,0.948291,0.120406,1620,0.924485,1848,0.292596,0.626457,0.881607,0.622748,2.009926,2.105639,79.821465,6.201619,0.325297,0.135046,8.907623,102.852463,0.100086,27200,40.014149,12.271824,6.867414,0.71674,60.738068,99.47612,25146],
[5,0.963883,289.111786,0.329091,0.952594,0.127129,1281,0.934794,1329,0.243432,0.598882,0.896488,0.678604,1.923423,1.88011,79.968826,4.378535,0.329017,0.155638,7.280628,97.070313,0.126351,17759,34.907391,8.176516,4.409596,0.803365,40.770561,94.317581,16601],
[5,0.96828,264.129944,0.32852,0.95647,0.124074,1740,0.937378,1797,0.241331,0.634873,0.900011,0.608472,2.004608,2.102218,84.405067,4.427886,0.328726,0.129055,7.73276,110.837379,0.124099,31890,36.783131,11.737496,5.530869,0.92066,67.043663,95.732254,29893],
[5,0.965517,242.238022,0.325508,0.961734,0.129486,1596,0.946213,1653,0.200339,0.603796,0.915949,0.659364,1.913669,1.925201,82.577667,3.394042,0.324969,0.152829,6.039383,101.481598,0.127572,27739,32.098572,7.93729,4.518105,0.842318,56.788128,86.457634,26247],
[5,0.957895,278.028992,0.327321,0.964743,0.131821,1638,0.947484,1710,0.18664,0.563779,0.92269,0.642573,1.832215,1.940799,92.23761,3.393454,0.325959,0.185375,6.034394,104.573898,0.127658,29705,33.622425,11.438144,4.60224,0.781176,69.18148,101.981682,28145],
[5,0.969589,256.842285,0.325855,0.964645,0.12778,1626,0.950267,1677,0.186248,0.590338,0.922817,0.637593,1.899533,1.989434,85.767593,3.226548,0.327135,0.163156,5.636649,102.551468,0.126413,28291,31.639406,11.339218,4.146311,0.912009,60.32233,92.38504,26884],
[5,0.966387,224.929352,0.324059,0.983784,0.12557,1725,0.983462,1785,0.072195,0.593351,0.966066,0.637002,1.925223,1.976336,101.269257,1.026201,0.324427,0.161085,2.149745,122.073494,0.119242,30234,21.422567,9.153716,1.386654,0.932025,75.075035,116.719475,29734],
[5,1.001631,300.757233,0.326969,0.973937,0.114165,1842,0.965998,1839,0.130819,0.577767,0.942824,0.619769,1.993507,2.031637,97.894928,2.162206,0.325589,0.173111,4.171859,114.240143,0.11857,31910,28.976643,13.890726,3.103314,0.694227,78.224716,123.447876,30825],
[5,1.014975,244.729889,0.329437,0.972424,0.104072,1830,0.956643,1803,0.144833,0.485064,0.939729,0.692289,1.91023,1.716551,103.110023,2.441796,0.329503,0.25984,4.903932,99.696228,0.112072,28992,31.855747,8.306499,3.408286,0.826055,64.144127,114.691544,27735],
[5,0.984496,306.612122,0.327266,0.96946,0.125773,1524,0.959746,1548,0.152337,0.570384,0.934521,0.652572,1.886139,1.928077,99.594414,2.430475,0.327745,0.179066,4.999976,114.49778,0.127016,24221,31.958038,8.789768,3.574899,0.821587,71.786087,115.527832,23246],
[5,0.984195,279.860321,0.326804,0.96521,0.102774,2055,0.944255,2088,0.190593,0.555202,0.920165,0.634797,2.059118,2.001867,101.488953,3.441503,0.3271,0.192895,6.96277,113.119194,0.105428,36577,37.879147,16.416008,5.019998,0.779991,79.448914,112.279274,34538],
[5,1.328042,299.014313,0.281853,0.966439,0.069177,2259,0.965593,1701,0.173522,0.659065,0.926328,0.571302,2.728261,2.240377,94.722122,2.801919,0.325917,0.111974,5.824137,130.0578,0.126354,29093,33.992092,17.803328,4.483671,0.82119,89.089226,123.13295,28092],
[5,0.99004,261.075195,0.328585,0.967546,0.126343,1491,0.952891,1506,0.168558,0.558524,0.928956,0.650496,1.859102,1.94699,96.725357,2.764606,0.328653,0.189504,5.658079,108.484261,0.129961,23456,33.592789,11.793193,3.63309,0.786538,63.858864,96.279366,22351],
[5,0.984424,284.565094,0.3261,0.965866,0.118675,1896,0.958984,1926,0.179886,0.705243,0.923688,0.545102,2.159453,2.339477,90.303566,3.006544,0.326843,0.083441,6.213906,139.209335,0.119926,35401,35.265091,15.575408,4.647409,0.929193,93.792725,114.775879,33949],
[5,1,300.403625,0.326406,0.966372,0.128263,1605,0.956318,1605,0.16709,0.585655,0.928711,0.665371,1.892689,1.88798,98.245056,2.721795,0.327766,0.167005,5.59432,116.506607,0.134121,27494,33.763157,6.555964,3.749259,0.710024,67.187927,108.876099,26293],
[5,0.987034,268.998718,0.327938,0.962575,0.124021,1827,0.952798,1851,0.199306,0.665434,0.91784,0.579976,2.052809,2.2513,88.693619,3.378924,0.327908,0.107785,6.465661,124.613869,0.126812,34575,35.093769,14.049045,4.209288,0.856885,75.489136,101.29657,32943],
[5,1.075229,337.040741,0.325523,0.954187,0.101846,1758,0.93746,1635,0.245928,0.620123,0.89945,0.621361,2.186567,2.070889,87.648514,4.793053,0.326538,0.138897,7.988166,111.49324,0.125601,26719,38.737522,11.496485,5.288894,0.891127,64.772133,126.448235,25048],
[5,1.043668,285.177185,0.321219,0.965235,0.095209,2151,0.950129,2061,0.188024,0.60372,0.920634,0.614969,2.231328,2.066045,96.395393,3.166469,0.323888,0.152318,6.461431,118.680908,0.109149,36895,35.764194,11.709446,4.83937,0.873351,78.218842,115.713966,35055],
[5,0.967391,335.458649,0.326276,0.96256,0.125193,1602,0.958357,1656,0.184565,0.683234,0.920057,0.607135,2.069767,2.190032,88.427338,2.994148,0.326973,0.096248,5.763081,129.284241,0.122253,26679,33.049721,9.548928,4.109481,0.873877,78.597244,126.519577,25568],
[5,0.98786,274.148376,0.327303,0.962739,0.105682,1953,0.949501,1977,0.200561,0.628074,0.916472,0.609417,2.160398,2.129619,93.071259,3.332178,0.328299,0.133765,6.721766,120.461815,0.108616,33783,36.207199,11.349506,4.39088,0.867394,72.242599,102.957901,32077],
[5,1.018122,287.663452,0.324674,0.962478,0.111303,1854,0.949182,1821,0.199386,0.632164,0.915942,0.600979,2.111617,2.19874,96.540955,3.524834,0.325232,0.130447,7.155752,126.120285,0.12155,32075,38.277061,13.339722,4.575498,0.877252,75.429817,112.174835,30445],
[5,0.946565,296.023438,0.324694,0.962137,0.124146,1488,0.940979,1572,0.196434,0.525817,0.916817,0.678223,1.823529,1.833374,97.722816,3.490817,0.320285,0.21875,6.758966,102.563438,0.11821,23246,36.636883,8.772933,4.15625,0.847334,55.487644,106.374138,21874],
[5,0.974074,267.528473,0.327418,0.96646,0.129328,1578,0.953456,1620,0.175076,0.587546,0.927388,0.656001,1.88756,1.949812,95.542412,3.086411,0.327892,0.16566,5.889355,113.665062,0.128699,26878,34.290192,9.476419,3.531146,0.822352,64.755554,96.450935,25627],
[5,1.145558,295.940063,0.324889,0.960268,0.090547,1818,0.942944,1587,0.215429,0.602896,0.911252,0.636821,2.28392,2.02776,91.204094,4.084125,0.328047,0.152561,7.051898,111.935646,0.126015,25256,36.413788,11.370978,4.633706,0.632803,59.058659,118.635445,23815],
[5,1.0176,279.206268,0.32506,0.968773,0.114471,1908,0.962361,1875,0.161437,0.657976,0.931927,0.591261,2.124722,2.206697,93.248558,2.599405,0.325622,0.112917,5.240794,128.900513,0.123171,34459,32.281033,9.466627,3.685436,0.802809,79.007439,106.758987,33162],
[5,0.761965,477.698029,0.325029,0.92686,0.1281,1815,0.895708,2382,0.420795,0.666316,0.832733,0.571357,2.021158,2.210949,92.299522,10.997183,0.323505,0.107409,16.224731,130.03566,0.083034,37491,56.1236,12.03651,12.546728,0.818828,81.431961,110.562927,33581],
[5,0.691729,478.361023,0.320871,0.925376,0.117543,1932,0.892279,2793,0.429243,0.654494,0.830556,0.597561,2.090909,2.180774,90.313362,11.147587,0.322974,0.115616,15.788228,123.834793,0.063033,39129,54.60738,11.754579,12.18924,0.879933,77.288742,96.310394,34914],
[5,0.440324,502.114563,0.325034,0.856414,0.101401,2280,0.736261,5178,0.870289,0.538403,0.633065,0.698268,2.039356,1.755866,90.240158,26.476332,0.30939,0.209352,37.558735,97.155106,0.026703,56973,76.999329,5.906392,26.695816,0.828466,57.892426,79.529709,41947],
[5,0.380195,607.079163,0.329047,0.890259,0.110693,2223,0.801451,5847,0.667349,0.551711,0.723281,0.664229,1.974245,1.894633,91.014145,19.715767,0.298826,0.197115,26.745831,100.621094,0.019964,54314,67.531876,7.953485,20.068239,0.659505,61.842533,72.295876,43530],
[5,0.836265,290.396759,0.325958,0.959806,0.124577,1854,0.947003,2217,0.214526,0.631669,0.912085,0.645932,1.993548,1.967245,84.701866,3.718848,0.324671,0.132457,6.535666,110.4468,0.091997,35983,34.255978,5.979109,4.663664,0.8586,64.947853,85.435814,34076],
[5,1.628483,145.427307,0.317268,0.946751,0.038943,3156,0.909833,1938,0.309309,0.582396,0.868049,0.669647,3.415584,1.847106,81.582077,2.912717,0.328368,0.168466,10.011868,95.958847,0.11351,33926,40.511196,5.019736,6.394245,0.672723,55.905907,63.298687,30867],
[5,1.271147,159.888672,0.315875,0.952973,0.044063,3291,0.918784,2589,0.260936,0.528118,0.889973,0.703735,3.064246,1.728282,88.589043,2.504325,0.313179,0.216915,8.641301,93.366165,0.077491,41334,39.202515,3.865791,5.548408,0.822874,56.213657,63.336151,37977],
[5,0.963753,235.77771,0.317674,0.931993,0.052408,2712,0.87271,2814,0.400837,0.514803,0.837093,0.735425,2.767347,1.600996,87.885124,5.677615,0.318872,0.23066,13.925886,90.211922,0.055778,35148,48.981297,2.882149,9.692434,0.633609,51.301086,53.959511,30674],
[5,1.101322,268.489197,0.318309,0.929726,0.046177,3000,0.890708,2724,0.39353,0.586186,0.838734,0.672084,3.151261,1.869461,88.040794,5.040944,0.321748,0.165214,13.176625,104.347298,0.062881,37130,47.410305,4.540793,9.45428,0.719581,62.155499,73.999702,33072],
[5,1.011511,194.335556,0.321784,0.936918,0.086427,2109,0.896466,2085,0.364745,0.579606,0.853446,0.711345,2.292391,1.750493,87.076225,4.710301,0.323963,0.173076,11.95737,101.746567,0.098641,34124,45.026558,2.557078,8.132174,0.544863,55.446995,41.734322,30591],
[5,0.850141,273.661011,0.312539,0.956604,0.083753,2706,0.929599,3183,0.244247,0.562739,0.900247,0.639731,2.297114,1.944592,92.992523,4.44275,0.313474,0.186766,8.360431,105.257309,0.065116,52499,39.690025,11.819439,6.023984,0.861511,71.508949,86.854179,48803],
[5,1.00312,231.265396,0.327713,0.964513,0.120897,1929,0.95663,1923,0.184776,0.665162,0.924062,0.623856,2.078664,2.079872,86.21685,2.827127,0.328869,0.10922,5.733668,121.0233,0.127168,37422,32.561413,6.599238,3.942419,0.843942,70.93837,76.926056,35799],
[5,0.948161,278.23999,0.328494,0.961504,0.131197,1701,0.950176,1794,0.203676,0.635851,0.917536,0.614209,1.950688,2.084897,90.048561,3.401406,0.328712,0.128606,6.370717,118.517937,0.124132,31792,34.405643,8.564831,4.510672,0.77495,71.070496,87.50016,30208]]


In [4]:
#membuat dataset target y
import numpy as np
y= np.array(dataset)[:,0]

#membuat dataset input X
import numpy as np
X = np.array(dataset)[:,1:21]

In [5]:
# Pisahkan dataset menjadi data latih dan uji dengan perbandingan 80:20
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=0)
#simpan data awal ke variabel
X_train_awal = X_train

D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
# Penyekalaan fitur dilakukan pada data latih dan uji.
# Detail kenapa ini penting dijelaskan di sini: http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

# Fungsi fit_transform hanya dilakukan di data latih
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#simpan data scaling ke variabel
X_train_scaling = X_train

In [7]:
print('jumlah data latih :', len(X_train))
print('jumlah data uji :', len(X_test))

jumlah data latih : 118
jumlah data uji : 51


In [18]:










# Latih kecerdasan buatan dengan data latih, menggunakan MLP-NN
from sklearn.neural_network import MLPClassifier
#X = [[0., 0.], [0., 1.], [1., 0.], [1., 1.]]
#y = [0, 0, 0, 1]
i=10
while (i<40):
  import time
  start = time.time()
  clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(i), random_state=1)
  print(clf.fit(X_train, y_train))
  end = time.time()
  print("training time: ",end - start)
  i=i+1
  
  result = clf.predict(X_test)
  print('Hasil Prediksi : ')
  print(result)
  
  # Cek kemampuan kecerdasan buatan dengan data uji 
  test_accuracy = clf.score(X_test, y_test)
  print('Akurasi Data Uji:', test_accuracy)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=10, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
training time:  1.888228416442871
Hasil Prediksi : 
[5. 3. 5. 3. 5. 3. 1. 1. 3. 5. 3. 3. 5. 3. 3. 3. 3. 2. 5. 4. 5. 3. 5. 5.
 5. 5. 1. 5. 5. 1. 1. 5. 5. 1. 3. 1. 1. 3. 4. 1. 5. 5. 5. 1. 3. 5. 1. 5.
 1. 3. 4.]
Akurasi Data Uji: 0.8627450980392157
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=11, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=23, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
training time:  0.8010330200195312
Hasil Prediksi : 
[5. 3. 5. 3. 5. 5. 1. 1. 3. 5. 5. 4. 5. 3. 3. 3. 3. 3. 5. 4. 5. 3. 5. 5.
 5. 5. 1. 5. 5. 1. 1. 5. 5. 1. 3. 1. 1. 3. 4. 1. 5. 5. 5. 1. 3. 5. 1. 5.
 1. 3. 4.]
Akurasi Data Uji: 0.8431372549019608
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=24, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=36, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
training time:  0.5390050411224365
Hasil Prediksi : 
[5. 3. 5. 3. 5. 3. 1. 1. 3. 5. 3. 4. 5. 3. 3. 3. 3. 2. 5. 4. 5. 3. 5. 5.
 5. 5. 1. 5. 5. 1. 1. 5. 5. 1. 3. 1. 1. 3. 1. 1. 5. 5. 5. 1. 3. 5. 1. 5.
 1. 3. 4.]
Akurasi Data Uji: 0.8627450980392157
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=37, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True

In [9]:
  clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(31), random_state=1)
  print(clf.fit(X_train, y_train))

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=31, learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)


In [10]:
# Lakukan proses cross-validation untuk mengetahui seberapa konsisten kemampuan kecerdasan buatan dengan data latih
# yang berbeda-beda subset nya. Dalam contoh ini dilakukan 10 kali cross-validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=clf, X=X_train, y=y_train, cv=10)
print(accuracies)

# Catat rerata akurasi dan standar deviasi 10 percobaan pelatihan
avg_accuracy = accuracies.mean()

std_accuracy = accuracies.std()
print('Akurasi: ', avg_accuracy)
print('SD: ', std_accuracy)

D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


[0.78571429 0.78571429 0.84615385 0.92307692 0.92307692 0.90909091
 0.90909091 1.         1.         1.        ]
Akurasi:  0.9081918081918081
SD:  0.07718884508962195


In [10]:
#prediksi  data test
result = clf.predict(X_test)
print('Hasil Prediksi : ')
print(result)

print('Nilai Target seharusnya : ')
print(y_test)

Hasil Prediksi : 
[5. 3. 5. 3. 5. 3. 1. 1. 3. 5. 3. 4. 5. 3. 3. 3. 3. 4. 5. 4. 5. 3. 5. 5.
 5. 5. 1. 5. 5. 1. 1. 5. 5. 1. 3. 1. 1. 3. 4. 1. 5. 5. 5. 1. 3. 5. 1. 5.
 1. 3. 4.]
Nilai Target seharusnya : 
[5. 3. 5. 3. 5. 3. 1. 1. 3. 5. 3. 4. 5. 5. 3. 2. 3. 4. 5. 4. 5. 5. 5. 5.
 3. 5. 1. 5. 5. 1. 1. 5. 5. 1. 3. 2. 1. 3. 4. 1. 5. 5. 5. 1. 3. 5. 1. 5.
 1. 3. 4.]


In [12]:
    # Cek kemampuan kecerdasan buatan dengan data uji 
    test_accuracy = clf.score(X_test, y_test)
    print('Akurasi Data Uji:', test_accuracy)
    from sklearn.metrics import accuracy_score
    print("akurasi : ",accuracy_score(y_test, result))

Akurasi Data Uji: 0.9019607843137255
akurasi :  0.9019607843137255


In [13]:



#Confusion Matriks Hasil Prediksi dengan Nilai Sebenarnya
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,result))

[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 11  0  1]
 [ 0  0  0  5  0]
 [ 0  0  2  0 19]]


In [14]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, result)


0.27450980392156865

In [15]:
#Banyak bobot yang digunakan
print([coef.shape for coef in clf.coefs_])

[(20, 31), (31, 5)]


In [81]:
print("weights between input and first hidden layer:")
print(clf.coefs_[0])
print("\nweights between first hidden and second hidden layer:")
print(clf.coefs_[1])
print("\nweights between second hidden and output:")
print(clf.coefs_[2])

weights between input and first hidden layer:
[[-5.10409879e-01  9.15687879e-01 -1.69578737e+00 -5.69432011e-01
   9.06570845e-02 -7.26072952e-01 -2.71262940e-01  3.54173102e-02
   4.80338476e-01 -4.97418889e-01 -1.84110888e-01 -2.18450315e-01
  -6.01239759e-01  9.52872667e-01 -7.21387445e-02  5.27041359e-01
  -8.11368504e-01  9.10655315e-01 -4.69188759e-01 -1.19214875e-01
  -4.35200107e-02  3.53409331e-01  2.07533452e-01  1.66384642e-01
   1.85237431e-01  8.59601586e-01  1.70770054e-01 -4.19077892e-01
  -3.60925714e-01 -4.07945635e-01 -6.53399465e-01]
 [ 1.44958243e+00 -3.53628693e-01 -3.53757472e-01 -2.17082037e-01
  -4.19616410e-01  1.35991873e+00 -4.12674930e-01 -2.13872174e-01
  -8.89849454e-01  8.25831632e-02  2.09079343e-01  5.08700451e-01
   2.28135727e+00 -2.62119267e-01 -3.23656831e-01  1.49300816e+00
   7.89715991e-01 -7.04001916e-01 -1.20496539e-01 -1.02187535e+00
   1.30804699e-01 -5.58653597e-01 -2.11981753e-01 -9.62894750e-01
  -3.13063344e-01 -1.69381869e-01 -3.61578123

IndexError: ignored

In [82]:
for i in range(len(clf.coefs_)):
    number_neurons_in_layer = clf.coefs_[i].shape[1]
    for j in range(number_neurons_in_layer):
        weights = clf.coefs_[i][:,j]
        print(i, j, weights, end=", ")
        print()
    print()

0 0 [-0.51040988  1.44958243  0.47468647  0.31777957  0.5986627   0.13528548
  0.10457908  1.70588316 -0.13387313  0.63924744  0.55450389  0.1582215
 -0.27637463  0.512075   -0.29477134 -0.22264242 -0.3251073  -0.70035731
 -0.1828623   0.26027282], 
0 1 [ 0.91568788 -0.35362869  0.10563819  0.45326182 -0.15092399 -0.05867653
  0.59842636 -0.72959118 -0.20594745  0.70112034  0.74724747 -0.84510102
  0.51518818  0.91722712  0.03386358 -0.17146029  0.44495675 -0.62172067
 -0.87723805  0.0408672 ], 
0 2 [-1.69578737 -0.35375747  0.22760188 -0.50560271  1.80811224  0.1268376
  0.40565227  1.14034855 -0.24806654  2.33619984 -0.17304451  0.12744847
 -0.39033808  0.49259073 -0.05728731 -0.55259921 -0.31511967 -1.93671954
 -0.46483987  1.86694283], 
0 3 [-0.56943201 -0.21708204  0.44633384  0.24577203  0.90162463  0.1934467
  0.54101665 -0.12627835  0.28543718  1.1279676  -0.20065096 -0.76954133
 -0.23451434  0.30870318  0.27121042 -0.19274806 -0.03896292 -0.65869685
 -0.0709482   1.28855119], 

In [83]:
print("Bias values for first hidden layer:")
print(clf.intercepts_[0])
print("\nBias values for second hidden layer:")
print(clf.intercepts_[1])
print("\nBias values for third hidden layer:")
print(clf.intercepts_[2])

Bias values for first hidden layer:
[-0.14243245  0.52272838 -0.58393281  0.34875502  0.68981847 -0.81702387
  0.02450947 -0.20096133 -0.26402988  0.02362011 -0.35700528 -0.69944217
  0.19410337 -0.17778621  0.42850183  0.81503874 -0.39672005  0.48593162
  0.47079943 -0.20340085  0.03701131  0.75415405 -0.43438789  0.18597732
 -0.42661912 -0.66916617  0.8187178  -0.48399597 -0.18341498  0.32903424
 -0.01645319]

Bias values for second hidden layer:
[ 1.20970813 -1.29715212  1.43869779 -1.02102714 -0.89177298]

Bias values for third hidden layer:


IndexError: ignored

In [84]:
print(classification_report(y_test,result))

             precision    recall  f1-score   support

        1.0       0.92      1.00      0.96        11
        2.0       0.00      0.00      0.00         2
        3.0       0.79      0.92      0.85        12
        4.0       1.00      1.00      1.00         5
        5.0       0.95      0.90      0.93        21

avg / total       0.87      0.90      0.89        51



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [85]:
prob_results = clf.predict_proba(X_test)
print(prob_results)

[[1.27576572e-018 8.38085320e-019 1.32566260e-009 6.07331573e-019
  9.99999999e-001]
 [8.70869362e-025 4.02220836e-015 1.00000000e+000 3.07043162e-019
  1.78680607e-016]
 [2.61225350e-033 9.16912173e-028 2.91578040e-012 5.74439527e-028
  1.00000000e+000]
 [4.14155429e-022 1.83303239e-012 1.00000000e+000 3.30735169e-019
  2.83976091e-025]
 [4.79460098e-029 2.17413244e-017 2.90080121e-006 1.58241535e-012
  9.99997099e-001]
 [2.78756328e-029 6.36392237e-015 9.99999840e-001 1.52060074e-012
  1.59604591e-007]
 [9.99999998e-001 2.19314573e-009 9.51349631e-020 3.21607113e-017
  1.31254738e-015]
 [1.00000000e+000 2.03954783e-030 1.78441779e-058 3.67634426e-045
  3.18003658e-020]
 [2.34726189e-014 2.31581862e-009 9.99567186e-001 6.10536646e-012
  4.32811393e-004]
 [6.42730913e-024 5.92195063e-021 2.60173953e-009 5.03280585e-021
  9.99999997e-001]
 [1.23907464e-026 1.52392512e-016 9.85607305e-001 1.58418815e-017
  1.43926950e-002]
 [6.01618595e-013 1.54735872e-012 1.16868498e-005 9.99988313e-001

In [72]:
#data uji awal
print('data uji sebelum scaling :')
print(X_train_awal)

data uji sebelum scaling :
[[6.88623000e-01 2.40389542e+02 3.18325000e-01 8.67205000e-01]
 [2.05517200e+00 3.75799042e+02 2.21690000e-01 7.30394000e-01]
 [2.44759600e+00 3.22056091e+02 2.57440000e-01 8.08634000e-01]
 [5.69095000e-01 4.09467926e+02 3.23682000e-01 8.53145000e-01]
 [7.47301000e-01 9.73269470e+02 2.60012000e-01 8.79558000e-01]
 [6.04963000e-01 4.43180634e+02 2.72850000e-01 7.67063000e-01]
 [9.36283000e-01 2.99587799e+02 3.22069000e-01 9.59963000e-01]
 [9.87860000e-01 2.74148376e+02 3.27303000e-01 9.62739000e-01]
 [1.00163100e+00 3.00757233e+02 3.26969000e-01 9.73937000e-01]
 [8.68613000e-01 3.44486908e+02 2.97397000e-01 8.03110000e-01]
 [4.83755000e-01 4.70305145e+02 3.27178000e-01 8.10634000e-01]
 [9.69589000e-01 2.56842285e+02 3.25855000e-01 9.64645000e-01]
 [1.75603900e+00 2.90921173e+02 2.90110000e-01 8.55390000e-01]
 [8.36265000e-01 2.90396759e+02 3.25958000e-01 9.59806000e-01]
 [2.97332000e+00 3.31332642e+02 2.41191000e-01 7.86225000e-01]
 [8.35443000e-01 4.60888977e

In [73]:
#data uji awal
print('data uji setelah scaling :')
print(X_train_scaling)

data uji setelah scaling :
[[-0.63148658 -0.81172301  0.59367776 -0.08538316]
 [ 1.77135814 -0.19613802 -2.82132665 -1.82713399]
 [ 2.46136921 -0.44045879 -1.55794995 -0.83105484]
 [-0.8416563  -0.04307594  0.7829899  -0.26438204]
 [-0.52831126  2.52002169 -1.4670575   0.07188379]
 [-0.7785885   0.11018537 -1.01337274 -1.36029827]
 [-0.19601846 -0.54260187  0.72598776  1.09552571]
 [-0.10532905 -0.65825201  0.91095317  1.13086717]
 [-0.08111508 -0.53728551  0.89914988  1.27342973]
 [-0.31500468 -0.33848608 -0.14590119 -0.90138128]
 [-0.99171222  0.23349608  0.90653577 -0.80559269]
 [-0.1374555  -0.73692721  0.859782    1.1551326 ]
 [ 1.24538348 -0.58200121 -0.40341801 -0.23580079]
 [-0.37188315 -0.58438525  0.86342194  1.09352694]
 [ 3.38576573 -0.39828667 -2.13217674 -1.11634545]
 [-0.3733285   0.19068925  0.03680251 -0.05090741]
 [-1.41461179  1.90337738  0.11165096 -1.05267735]
 [-0.22722706 -0.90727718  0.73294958  1.24324435]
 [-0.82591045  0.2777473   0.91335624 -0.18743544]
 [ 0

In [74]:
import tensorflow as tf
tf.test.gpu_device_name()

'/device:GPU:0'

In [75]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 6793265020012298478, name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 11288962663
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 14094621658026299123
 physical_device_desc: "device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7"]

In [76]:
!cat /proc/meminfo

MemTotal:       13341832 kB
MemFree:          603656 kB
MemAvailable:   11643368 kB
Buffers:          165596 kB
Cached:         10787544 kB
SwapCached:            0 kB
Active:          3882068 kB
Inactive:        8052816 kB
Active(anon):    1152204 kB
Inactive(anon):    85480 kB
Active(file):    2729864 kB
Inactive(file):  7967336 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:              1288 kB
Writeback:             0 kB
AnonPages:        981824 kB
Mapped:           408680 kB
Shmem:            255948 kB
Slab:             630840 kB
SReclaimable:     595928 kB
SUnreclaim:        34912 kB
KernelStack:        3440 kB
PageTables:         7836 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6670916 kB
Committed_AS:    2496384 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
AnonHugePages:         0 kB
HugePages_Total: 

In [77]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU @ 2.30GHz
stepping	: 0
microcode	: 0x1
cpu MHz		: 2300.000
cache size	: 46080 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm kaiser fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms xsaveopt
bugs		:
bogomips	: 4600.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU @ 2.30GHz
stepping	: 0
microcode	: 0x1
cpu MHz		: 2300.000
cache s