In [1]:
import pandas as pd
import numpy as np
df = pd.read_excel('Urut-Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0)

In [2]:
'''
index : feature name
0 : 'Jenis', 
1 : 'KIperKP', 
2 : 'KontrasP', 
3 : 'Solidity_Inti', 
4 : 'HomogenitasP',
5 : 'Circularity_Inti', 
6 : 'Keliling_Inti', 
7 : 'LIperLP ', 
8 : 'KelilingP',
9 : 'EntropiP', 
10 : 'LuasNormal_P', 
11 : 'EnergiP', 
12 : 'Homogenitas_Inti',
13 : 'KelilingNormal_I',
14 : 'Entropi_Inti',
15 : 'Granularity_Inti',
16 : 'RerataGP',
17 : 'SolidityP',
18 : 'Energi_Inti',
19 : 'RerataRP',
20 : 'RerataR_Inti', 
21 : 'CircularityP',
22 : 'LuasP', 
23 : 'GranularityP',
24 : 'RerataG_Inti',
25 : 'RerataBP', 
26 : 'Eccentricity', 
27 : 'RerataB_Inti',
28 : 'Kontras_Inti',
29 : 'Luas_Inti']
'''


head = ['Jenis', 'KIperKP', 'KontrasP', 'Solidity_Inti', 'HomogenitasP',
        'Circularity_Inti', 'Keliling_Inti', 'LIperLP ', 'KelilingP',
        'EntropiP', 'LuasNormal_P', 'EnergiP', 'Homogenitas_Inti',
        'KelilingNormal_I', 'Entropi_Inti', 'Granularity_Inti',
        'RerataGP', 'SolidityP', 'Energi_Inti', 'RerataRP',
        'RerataR_Inti', 'CircularityP', 'LuasP', 'GranularityP',
        'RerataG_Inti', 'RerataBP', 'Eccentricity', 'RerataB_Inti',
        'Kontras_Inti', 'Luas_Inti']

In [3]:
df[0:0]
lc =df.drop( head[1], axis=1)
lc[0:0]

Empty DataFrame
Columns: [Jenis, KontrasP, Solidity_Inti, HomogenitasP, Circularity_Inti, Keliling_Inti, LIperLP , KelilingP, EntropiP, LuasNormal_P, EnergiP, Homogenitas_Inti, KelilingNormal_I, Entropi_Inti, Granularity_Inti, RerataGP, SolidityP, Energi_Inti, RerataRP, RerataR_Inti, CircularityP, LuasP, GranularityP, RerataG_Inti, RerataBP, Eccentricity, RerataB_Inti, Kontras_Inti, Luas_Inti]
Index: []

[0 rows x 29 columns]

In [6]:
lc =df.drop( head[1], axis=1)
lc[0:0]

Empty DataFrame
Columns: [Jenis, KontrasP, Solidity_Inti, HomogenitasP, Circularity_Inti, Keliling_Inti, LIperLP , KelilingP, EntropiP, LuasNormal_P, EnergiP, Homogenitas_Inti, KelilingNormal_I, Entropi_Inti, Granularity_Inti, RerataGP, SolidityP, Energi_Inti, RerataRP, RerataR_Inti, CircularityP, LuasP, GranularityP, RerataG_Inti, RerataBP, Eccentricity, RerataB_Inti, Kontras_Inti, Luas_Inti]
Index: []

[0 rows x 29 columns]

In [7]:
data = [ ]
i=10
k=1
#for k in [11,16,21,26,30]:
while(k<30):
    print("fitur ke: ",k)
    daf = pd.read_excel('Urut-Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0)
    df = daf.drop(head[k], axis=1)
    print(df[0:0])
    #membuat dataset target y
    import numpy as np
    y= np.array(df)[:,0]

    #membuat dataset input X
    X = np.array(df)[:,1:29]

    #keterangan jumlah fitur
    #data.append([k])

    # Pisahkan dataset menjadi data latih dan uji dengan perbandingan 80:20
    from sklearn.cross_validation import train_test_split
    X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=0)

    # Penyekalaan fitur dilakukan pada data latih dan uji.
    # Detail kenapa ini penting dijelaskan di sini: http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()

    # Fungsi fit_transform hanya dilakukan di data latih
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)

    # Latih kecerdasan buatan dengan data latih, menggunakan MLP-NN
    from sklearn.neural_network import MLPClassifier
    import time
    clf = MLPClassifier(activation='tanh',solver='adam', alpha=1e-5, max_iter=2000,
                hidden_layer_sizes=(10), random_state=1)
    start = time.time()    
    print(clf.fit(X_train, y_train))
    end = time.time()
    waktuTrain = end - start


    #prediksi
    start = time.time()
    result = clf.predict(X_test)
    end = time.time()
    waktuTest = end - start

    #Confusion Matriks Hasil Prediksi dengan Nilai Sebenarnya
    from sklearn.metrics import classification_report,confusion_matrix, roc_auc_score
    print(confusion_matrix(y_test,result))

    # Cek kemampuan kecerdasan buatan dengan data uji 
    test_accuracy = clf.score(X_test, y_test)
    print("akurasi uji: ",test_accuracy)

    # Cek kemampuan kecerdasan buatan dengan data uji 
    train_accuracy = clf.score(X_train, y_train)

    data.append( [k, i,'{0:.2f}'.format(test_accuracy)]) 

    print()  

    k=k+1


fitur ke:  1
Empty DataFrame
Columns: [Jenis, KontrasP, Solidity_Inti, HomogenitasP, Circularity_Inti, Keliling_Inti, LIperLP , KelilingP, EntropiP, LuasNormal_P, EnergiP, Homogenitas_Inti, KelilingNormal_I, Entropi_Inti, Granularity_Inti, RerataGP, SolidityP, Energi_Inti, RerataRP, RerataR_Inti, CircularityP, LuasP, GranularityP, RerataG_Inti, RerataBP, Eccentricity, RerataB_Inti, Kontras_Inti, Luas_Inti]
Index: []

[0 rows x 29 columns]


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=10, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 11  0  1]
 [ 0  1  0  4  0]
 [ 0  0  1  0 20]]
akurasi uji:  0.9019607843137255

fitur ke:  2
Empty DataFrame
Columns: [Jenis, KIperKP, Solidity_Inti, HomogenitasP, Circularity_Inti, Keliling_Inti, LIperLP , KelilingP, EntropiP, LuasNormal_P, EnergiP, Homogenitas_Inti, KelilingNormal_I, Entropi_Inti, Granularity_Inti, RerataGP, SolidityP, Energi_Inti, RerataRP, RerataR_Inti, CircularityP, LuasP, GranularityP, RerataG_Inti, RerataBP, Eccentricity, RerataB_Inti, Kontras_Inti, Luas_Inti]
Index: []

[0 rows x 29 columns]
MLPCla

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=10, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 1  1  0  0  0]
 [ 0  0 10  0  2]
 [ 0  1  1  3  0]
 [ 0  0  1  0 20]]
akurasi uji:  0.8823529411764706

fitur ke:  11
Empty DataFrame
Columns: [Jenis, KIperKP, KontrasP, Solidity_Inti, HomogenitasP, Circularity_Inti, Keliling_Inti, LIperLP , KelilingP, EntropiP, LuasNormal_P, Homogenitas_Inti, KelilingNormal_I, Entropi_Inti, Granularity_Inti, RerataGP, SolidityP, Energi_Inti, RerataRP, RerataR_Inti, CircularityP, LuasP, GranularityP, RerataG_Inti, RerataBP, Eccentricity, RerataB_Inti, Kontras_Inti, Luas_Inti]
Index: []

[0 rows x 29 columns]
MLPC

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=10, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[10  1  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 10  0  2]
 [ 0  1  0  4  0]
 [ 0  0  1  0 20]]
akurasi uji:  0.8627450980392157

fitur ke:  20
Empty DataFrame
Columns: [Jenis, KIperKP, KontrasP, Solidity_Inti, HomogenitasP, Circularity_Inti, Keliling_Inti, LIperLP , KelilingP, EntropiP, LuasNormal_P, EnergiP, Homogenitas_Inti, KelilingNormal_I, Entropi_Inti, Granularity_Inti, RerataGP, SolidityP, Energi_Inti, RerataRP, CircularityP, LuasP, GranularityP, RerataG_Inti, RerataBP, Eccentricity, RerataB_Inti, Kontras_Inti, Luas_Inti]
Index: []

[0 rows x 29 columns]
MLPClassi

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=10, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[10  1  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 12  0  0]
 [ 0  1  0  4  0]
 [ 0  0  1  0 20]]
akurasi uji:  0.9019607843137255

fitur ke:  29
Empty DataFrame
Columns: [Jenis, KIperKP, KontrasP, Solidity_Inti, HomogenitasP, Circularity_Inti, Keliling_Inti, LIperLP , KelilingP, EntropiP, LuasNormal_P, EnergiP, Homogenitas_Inti, KelilingNormal_I, Entropi_Inti, Granularity_Inti, RerataGP, SolidityP, Energi_Inti, RerataRP, RerataR_Inti, CircularityP, LuasP, GranularityP, RerataG_Inti, RerataBP, Eccentricity, RerataB_Inti, Kontras_Inti]
Index: []

[0 rows x 29 columns]
MLPCla

In [8]:
data

[[1, 10, '0.90'],
 [2, 10, '0.86'],
 [3, 10, '0.86'],
 [4, 10, '0.86'],
 [5, 10, '0.86'],
 [6, 10, '0.84'],
 [7, 10, '0.86'],
 [8, 10, '0.86'],
 [9, 10, '0.86'],
 [10, 10, '0.88'],
 [11, 10, '0.88'],
 [12, 10, '0.86'],
 [13, 10, '0.84'],
 [14, 10, '0.88'],
 [15, 10, '0.84'],
 [16, 10, '0.84'],
 [17, 10, '0.82'],
 [18, 10, '0.88'],
 [19, 10, '0.86'],
 [20, 10, '0.86'],
 [21, 10, '0.86'],
 [22, 10, '0.88'],
 [23, 10, '0.84'],
 [24, 10, '0.90'],
 [25, 10, '0.84'],
 [26, 10, '0.86'],
 [27, 10, '0.86'],
 [28, 10, '0.90'],
 [29, 10, '0.88']]

In [14]:
#save data ke csv
#np.savetxt("Feature Elimination.csv", data)

In [32]:
data = [ ]
k=1
#for k in [11,16,21,26,30]:
while(k<2):
    print("fitur ke: ",k)
    df = pd.read_excel('Urut-Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0)

    #membuat dataset target y
    import numpy as np
    y= np.array(df)[:,0]

    #membuat dataset input X
    X = np.array(df)[:,1:29]

    #keterangan jumlah fitur
    data.append([29,k])
    
    # Pisahkan dataset menjadi data latih dan uji dengan perbandingan 80:20
    from sklearn.cross_validation import train_test_split
    X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=0)

    # Penyekalaan fitur dilakukan pada data latih dan uji.
    # Detail kenapa ini penting dijelaskan di sini: http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()

    # Fungsi fit_transform hanya dilakukan di data latih
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)

    # Latih kecerdasan buatan dengan data latih, menggunakan MLP-NN
    from sklearn.neural_network import MLPClassifier
    from sklearn.metrics import mean_squared_error, r2_score
    import time

    i=21
   
    while (i<23):
      clf = MLPClassifier(activation='relu',solver='lbfgs', alpha=1e-5, max_iter=2000,
                        hidden_layer_sizes=(i), random_state=1)
      start = time.time()    
      print(clf.fit(X_train, y_train))
      end = time.time()
      waktuTrain = end - start

     
       #prediksi
      start = time.time()
      result = clf.predict(X_test)
      end = time.time()
      waktuTest = end - start

      #Confusion Matriks Hasil Prediksi dengan Nilai Sebenarnya
      from sklearn.metrics import classification_report,confusion_matrix, roc_auc_score
      print(confusion_matrix(y_test,result))

      # Cek kemampuan kecerdasan buatan dengan data uji 
      test_accuracy = clf.score(X_test, y_test)
      print("akurasi uji: ",test_accuracy)

      # Cek kemampuan kecerdasan buatan dengan data uji 
      train_accuracy = clf.score(X_train, y_train)

      data.append( [i,'{0:.2f}'.format(test_accuracy), '{0:.2f}'.format(clf.loss_), '{0:.2f}'.format(clf.n_iter_), '{0:.2f}'.format(waktuTrain), '{0:.2f}'.format(waktuTest)]) 
      print()  
      i=i+1
      k=k+1

fitur ke:  1
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=21, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[ 9  2  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 10  0  2]
 [ 0  1  1  3  0]
 [ 0  0  1  0 20]]
akurasi uji:  0.8235294117647058

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=22, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[ 9  

In [33]:
data

[[29, 1],
 [21, '0.82', '0.00', '18.00', '0.09', '0.00'],
 [22, '0.82', '0.00', '19.00', '0.05', '0.00']]

In [17]:
data = [ ]
i=10
k=1
#for k in [11,16,21,26,30]:
while (i<22):
    i=i+5

    df = pd.read_excel('Urut-Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0)

    import numpy as np
    y= np.array(df)[:,0]
    #membuat dataset input X
    X = np.array(df)[:,1:30]

    # Pisahkan dataset menjadi data latih dan uji dengan perbandingan 80:20
    from sklearn.cross_validation import train_test_split
    X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=0)

    # Penyekalaan fitur dilakukan pada data latih dan uji.
    # Detail kenapa ini penting dijelaskan di sini: http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()

    # Fungsi fit_transform hanya dilakukan di data latih
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)

    # Latih kecerdasan buatan dengan data latih, menggunakan MLP-NN
    from sklearn.neural_network import MLPClassifier
    from sklearn.metrics import mean_squared_error, r2_score
    import time


    clf = MLPClassifier(activation='relu',solver='lbfgs', alpha=1e-5, max_iter=2000,
                hidden_layer_sizes=(i), random_state=1)
    start = time.time()    
    print(clf.fit(X_train, y_train))
    end = time.time()
    waktuTrain = end - start


    #prediksi
    start = time.time()
    result = clf.predict(X_test)
    end = time.time()
    waktuTest = end - start

    #Confusion Matriks Hasil Prediksi dengan Nilai Sebenarnya
    from sklearn.metrics import classification_report,confusion_matrix, roc_auc_score
    print(confusion_matrix(y_test,result))

    # Cek kemampuan kecerdasan buatan dengan data uji 
    test_accuracy = clf.score(X_test, y_test)
    print("akurasi uji: ",test_accuracy)

    # Cek kemampuan kecerdasan buatan dengan data uji 
    train_accuracy = clf.score(X_train, y_train)

    data.append( [k, i,'{0:.2f}'.format(test_accuracy)]) 
    print()  

    k=k+1


MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=15, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[10  0  0  0  1]
 [ 1  0  1  0  0]
 [ 0  0 12  0  0]
 [ 1  0  1  3  0]
 [ 1  0  1  0 19]]
akurasi uji:  0.8627450980392157

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=20, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[10  1  0  0  0]
 

In [34]:
data

[[29, 1],
 [21, '0.82', '0.00', '18.00', '0.09', '0.00'],
 [22, '0.82', '0.00', '19.00', '0.05', '0.00']]

In [25]:
X_train[:0]

array([], shape=(0, 29), dtype=float64)