In [4]:
import pandas as pd
import numpy as np
dataset = pd.read_excel('feature elimination.xlsx', header=0)

In [5]:
dataset

Jenis  Solidity_Inti  Keliling_Inti  KelilingNormal_I  Granularity_Inti  \
0        1       0.295574           2235          2.337866        104.162460   
1        1       0.276264           4125          3.669929         63.401608   
2        1       0.274679           7965          6.926087         65.156616   
3        1       0.263279           8115          7.431319         66.084785   
4        1       0.228109           9930          8.316583         66.808174   
5        1       0.242267           6978          6.533708         53.952385   
6        1       0.242138           7173          5.766077         63.488342   
7        1       0.273889           4785          4.139273         66.707657   
8        1       0.268239           5421          5.346154         60.061481   
9        1       0.272751           6276          5.664260         58.653553   
10       1       0.253547          12681          9.149351         68.033195   
11       1       0.270890           6021          5.347247         60.322857   
12       1       0.268333           5214          4.740000         62.240177   
13       1       0.266154           6654          6.472763         51.220791   
14       1       0.280247           4656          4.409091         65.864754   
15       1       0.244770           7629          7.553465         59.778351   
16       1       0.297397           3213          3.077586         59.083771   
17       1       0.272937           7083          5.922241         61.436592   
18       1       0.245882           7242          6.137288         63.979141   
19       1       0.272850           3657          3.271020         58.047604   
20       1       0.275053           6645          5.738342         62.431053   
21       1       0.284168           5985          5.421196         57.861412   
22       1       0.241191           9027          7.728596         57.068806   
23       1       0.256130           9855          8.198835         70.940239   
24       1       0.257440           5955          5.826810         67.048485   
25       1       0.263526           4473          4.188202         61.077282   
26       1       0.272726           8682          6.255043         59.589523   
27       1       0.275885           5583          4.637043         55.512218   
28       1       0.258231           4467          3.904720         64.331688   
29       1       0.267715           3966          4.157233         58.267696   
..     ...            ...            ...               ...               ...   
139      5       0.329437           1830          1.910230        103.110023   
140      5       0.327266           1524          1.886139         99.594414   
141      5       0.326804           2055          2.059118        101.488953   
142      5       0.281853           2259          2.728261         94.722122   
143      5       0.328585           1491          1.859102         96.725357   
144      5       0.326100           1896          2.159453         90.303566   
145      5       0.326406           1605          1.892689         98.245056   
146      5       0.327938           1827          2.052809         88.693619   
147      5       0.325523           1758          2.186567         87.648514   
148      5       0.321219           2151          2.231328         96.395393   
149      5       0.326276           1602          2.069767         88.427338   
150      5       0.327303           1953          2.160398         93.071259   
151      5       0.324674           1854          2.111617         96.540955   
152      5       0.324694           1488          1.823529         97.722816   
153      5       0.327418           1578          1.887560         95.542412   
154      5       0.324889           1818          2.283920         91.204094   
155      5       0.325060           1908          2.124722         93.248558   
156      5       0.325029           1815          2.021158         92.299522   
157  

In [11]:
data = [ ]
k=5
#for k in [11,16,21,26,30]:
while(k<31):
    print("jumlah fitur: ",k)
    #membuat dataset target y
    import numpy as np
    y= np.array(dataset)[:,0]

    #membuat dataset input X
    X = np.array(dataset)[:,1:k]

    #keterangan jumlah fitur
    data.append([29,k])
    
    # Pisahkan dataset menjadi data latih dan uji dengan perbandingan 80:20
    from sklearn.cross_validation import train_test_split
    X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=0)

    # Penyekalaan fitur dilakukan pada data latih dan uji.
    # Detail kenapa ini penting dijelaskan di sini: http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()

    # Fungsi fit_transform hanya dilakukan di data latih
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)

    # Latih kecerdasan buatan dengan data latih, menggunakan MLP-NN
    from sklearn.neural_network import MLPClassifier
    from sklearn.metrics import mean_squared_error, r2_score
    import time

    i=10
   
    while (i<80):
      clf = MLPClassifier(activation='tanh',solver='adam', alpha=1e-5, max_iter=3000,
                        hidden_layer_sizes=(i), random_state=1)
      start = time.time()    
      print(clf.fit(X_train, y_train))
      end = time.time()
      waktuTrain = end - start
      if(i>30):
        i=i+5
      elif(i<=30):  
        i=i+1

       #prediksi
      start = time.time()
      result = clf.predict(X_test)
      end = time.time()
      waktuTest = end - start

      #Confusion Matriks Hasil Prediksi dengan Nilai Sebenarnya
      from sklearn.metrics import classification_report,confusion_matrix, roc_auc_score
      print(confusion_matrix(y_test,result))

      # Cek kemampuan kecerdasan buatan dengan data uji 
      test_accuracy = clf.score(X_test, y_test)
      print("akurasi uji: ",test_accuracy)

      # Cek kemampuan kecerdasan buatan dengan data uji 
      train_accuracy = clf.score(X_train, y_train)

      data.append( [i-1,float('{0:.4f}'.format(test_accuracy))*100, '{0:.4f}'.format(clf.loss_), '{0:.0f}'.format(clf.n_iter_), '{0:.4f}'.format(waktuTrain), '{0:.4f}'.format(waktuTest)]) 
      print()  
    k=k+1

jumlah fitur:  5
MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=10, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 1  0  0  0  1]
 [ 0  0 10  0  2]
 [ 1  1  0  3  0]
 [ 0  0  1  0 20]]
akurasi uji:  0.8627450980392157

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=11, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=25, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 1  0  0  0  1]
 [ 0  0  9  1  2]
 [ 0  2  0  3  0]
 [ 0  0  1  0 20]]
akurasi uji:  0.8431372549019608

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=26, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=76, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 1  0  0  0  1]
 [ 0  0 10  0  2]
 [ 0  2  0  3  0]
 [ 0  0  2  0 19]]
akurasi uji:  0.8431372549019608

jumlah fitur:  6
MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=10, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=24, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 12  0  0]
 [ 1  0  0  4  0]
 [ 0  0  4  0 17]]
akurasi uji:  0.8627450980392157

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=25, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=71, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 12  0  0]
 [ 0  1  0  4  0]
 [ 0  0  4  0 17]]
akurasi uji:  0.8627450980392157

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=76, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=23, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 12  0  0]
 [ 1  0  0  4  0]
 [ 0  0  4  0 17]]
akurasi uji:  0.8627450980392157

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=24, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=66, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 12  0  0]
 [ 1  0  0  4  0]
 [ 0  0  4  0 17]]
akurasi uji:  0.8627450980392157

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=71, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=22, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 12  0  0]
 [ 1  0  0  4  0]
 [ 0  0  3  0 18]]
akurasi uji:  0.8823529411764706

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=23, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=61, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 12  0  0]
 [ 1  0  0  4  0]
 [ 0  0  4  0 17]]
akurasi uji:  0.8627450980392157

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=66, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=21, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 12  0  0]
 [ 0  0  1  4  0]
 [ 0  0  4  0 17]]
akurasi uji:  0.8627450980392157

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=22, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[11  0  0  0  0]
 [ 

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=56, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[10  1  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 12  0  0]
 [ 0  0  1  4  0]
 [ 0  0  2  1 18]]
akurasi uji:  0.8627450980392157

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=61, learning_rate='constant',
       learning_rate_init=0.001, max_iter=3000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
[[10  1  0  0  0]
 [ 

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [ ]:
data