In [5]:
import pandas as pd
import numpy as np
ar = [[1, 2, 3], [4, 5, 6]]
print(ar)
df = pd.DataFrame(np.array(ar))

# Use the `shape` property
print()
print(df.shape)

# Or use the `len()` function with the `index` property
print(len(df.index))
df

[[1, 2, 3], [4, 5, 6]]

(2, 3)
2


0  1  2
0  1  2  3
1  4  5  6

In [10]:
#Rename Columns name
df.columns = (['satu','dua','tiga'])
df

satu  dua  tiga
0     1    2     3
1     4    5     6

In [12]:
#Reordering Columns by name
df = df[['dua', 'tiga', 'satu']]
df

dua  tiga  satu
0    2     3     1
1    5     6     4

In [3]:
import pandas as pd
import numpy as np
df = pd.read_excel('Urut-Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0)

In [2]:
head = ['Jenis', 'KIperKP', 'KontrasP', 'Solidity_Inti', 'HomogenitasP',
        'Circularity_Inti', 'Keliling_Inti', 'LIperLP ', 'KelilingP',
        'EntropiP', 'LuasNormal_P', 'EnergiP', 'Homogenitas_Inti',
        'KelilingNormal_I', 'Entropi_Inti', 'Granularity_Inti',
        'RerataGP', 'SolidityP', 'Energi_Inti', 'RerataRP',
        'RerataR_Inti', 'CircularityP', 'LuasP', 'GranularityP',
        'RerataG_Inti', 'RerataBP', 'Eccentricity', 'RerataB_Inti',
        'Kontras_Inti', 'Luas_Inti']

In [18]:
#df.drop([head[0], head[i]], axis=1)
df

Jenis   KIperKP    KontrasP  Solidity_Inti  HomogenitasP  \
0        1  1.041958  411.989685       0.295574      0.910293   
1        1  0.867508  423.807465       0.276264      0.819063   
2        1  2.514205  373.516144       0.274679      0.825400   
3        1  2.064885  411.183746       0.263279      0.815429   
4        1  2.439204  449.707581       0.228109      0.758283   
5        1  2.581576  315.389404       0.242267      0.777450   
6        1  1.166911  481.051636       0.242138      0.765215   
7        1  1.000627  429.702301       0.273889      0.797555   
8        1  1.757782  385.725739       0.268239      0.797553   
9        1  1.874552  343.112488       0.272751      0.782707   
10       1  1.423712  525.832275       0.253547      0.782831   
11       1  1.873950  328.263489       0.270890      0.828853   
12       1  1.591575  327.084381       0.268333      0.841546   
13       1  2.153398  313.615784       0.266154      0.806441   
14       1  1.183829  406.449707       0.280247      0.790041   
15       1  3.045509  367.868591       0.244770      0.780308   
16       1  0.868613  344.486908       0.297397      0.803110   
17       1  1.663848  344.638031       0.272937      0.837263   
18       1  1.299946  484.311188       0.245882      0.748368   
19       1  0.604963  443.180634       0.272850      0.767063   
20       1  1.355569  435.087860       0.275053      0.831467   
21       1  1.469072  365.639160       0.284168      0.834321   
22       1  2.973320  331.332642       0.241191      0.786225   
23       1  3.107852  362.650787       0.256130      0.810095   
24       1  2.447596  322.056091       0.257440      0.808634   
25       1  1.485060  321.116669       0.263526      0.812676   
26       1  1.727761  315.770508       0.272726      0.710595   
27       1  1.007035  412.668671       0.275885      0.768220   
28       1  0.952655  388.664093       0.258231      0.794497   
29       1  1.400424  312.048431       0.267715      0.811480   
..     ...       ...         ...            ...           ...   
139      5  1.014975  244.729889       0.329437      0.972424   
140      5  0.984496  306.612122       0.327266      0.969460   
141      5  0.984195  279.860321       0.326804      0.965210   
142      5  1.328042  299.014313       0.281853      0.966439   
143      5  0.990040  261.075195       0.328585      0.967546   
144      5  0.984424  284.565094       0.326100      0.965866   
145      5  1.000000  300.403625       0.326406      0.966372   
146      5  0.987034  268.998718       0.327938      0.962575   
147      5  1.075229  337.040741       0.325523      0.954187   
148      5  1.043668  285.177185       0.321219      0.965235   
149      5  0.967391  335.458649       0.326276      0.962560   
150      5  0.987860  274.148376       0.327303      0.962739   
151      5  1.018122  287.663452       0.324674      0.962478   
152      5  0.946565  296.023438       0.324694      0.962137   
153      5  0.974074  267.528473       0.327418      0.966460   
154      5  1.145558  295.940063       0.324889      0.960268   
155      5  1.017600  279.206268       0.325060      0.968773   
156      5  0.761965  477.698029       0.325029      0.926860   
157      5  0.691729  478.361023       0.320871      0.925376   
158      5  0.440324  502.114563       0.325034      0.856414   
159      5  0.380195  607.079163       0.329047      0.890259   
160      5  0.836265  290.396759       0.325958      0.959806   
161      5  1.628483  145.427307       0.317268      0.946751   
162      5  1.271147  159.888672       0.315875      0.952973   
163      5  0.963753  235.777710       0.317674      0.931993   
164      5  1.101322  268.489197       0.318309      0.929726   
165      5  1.011511  194.335556       0.321784      0.936918   
166      5  0.850141  273.661011       0.312539      0.956604   
167      5  1.003120  231.265396       0.327713      0.964513   
168      5  0.948161  278.239990       0

In [10]:
import numpy as np
dataset = np.array(df)

In [13]:
dataset

array([[1.00000000e+00, 1.04195800e+00, 4.11989685e+02, ...,
        6.13139190e+01, 1.25540268e+02, 2.23330000e+04],
       [1.00000000e+00, 8.67508000e-01, 4.23807465e+02, ...,
        2.66922700e+01, 7.15319290e+01, 3.10250000e+04],
       [1.00000000e+00, 2.51420500e+00, 3.73516144e+02, ...,
        3.11381280e+01, 1.27077431e+02, 3.68320000e+04],
       ...,
       [5.00000000e+00, 8.50141000e-01, 2.73661011e+02, ...,
        7.15089490e+01, 8.68541790e+01, 4.88030000e+04],
       [5.00000000e+00, 1.00312000e+00, 2.31265396e+02, ...,
        7.09383700e+01, 7.69260560e+01, 3.57990000e+04],
       [5.00000000e+00, 9.48161000e-01, 2.78239990e+02, ...,
        7.10704960e+01, 8.75001600e+01, 3.02080000e+04]])

In [12]:
"""#save data ke csv
np.savetxt("Matrix Korelasi.csv", corr_matrix, delimiter=",")"""

'#save data ke csv\nnp.savetxt("Matrix Korelasi.csv", corr_matrix, delimiter=",")'

In [5]:
#membuat dataset target y
import numpy as np
y= np.array(dataset)[:,0]

#membuat dataset input X
X = np.array(dataset)[:,1:30]

In [6]:
X

array([[1.04195800e+00, 4.11989685e+02, 2.95574000e-01, ...,
        6.13139190e+01, 1.25540268e+02, 2.23330000e+04],
       [8.67508000e-01, 4.23807465e+02, 2.76264000e-01, ...,
        2.66922700e+01, 7.15319290e+01, 3.10250000e+04],
       [2.51420500e+00, 3.73516144e+02, 2.74679000e-01, ...,
        3.11381280e+01, 1.27077431e+02, 3.68320000e+04],
       ...,
       [8.50141000e-01, 2.73661011e+02, 3.12539000e-01, ...,
        7.15089490e+01, 8.68541790e+01, 4.88030000e+04],
       [1.00312000e+00, 2.31265396e+02, 3.27713000e-01, ...,
        7.09383700e+01, 7.69260560e+01, 3.57990000e+04],
       [9.48161000e-01, 2.78239990e+02, 3.28494000e-01, ...,
        7.10704960e+01, 8.75001600e+01, 3.02080000e+04]])

In [7]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
# Pisahkan dataset menjadi data latih dan uji dengan perbandingan 80:20
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=0)
#simpan data awal ke variabel
X_train_awal = X_train

D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [29]:
y_test

array([5., 3., 5., 3., 5., 3., 1., 1., 3., 5., 3., 4., 5., 5., 3., 2., 3.,
       4., 5., 4., 5., 5., 5., 5., 3., 5., 1., 5., 5., 1., 1., 5., 5., 1.,
       3., 2., 1., 3., 4., 1., 5., 5., 5., 1., 3., 5., 1., 5., 1., 3., 4.])

In [10]:
# Penyekalaan fitur dilakukan pada data latih dan uji.
# Detail kenapa ini penting dijelaskan di sini: http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

# Fungsi fit_transform hanya dilakukan di data latih
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#simpan data scaling ke variabel
X_train_scaling = X_train

In [17]:
# Latih kecerdasan buatan dengan data latih, menggunakan MLP-NN
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(activation='relu',solver='lbfgs',alpha=1e-5, max_iter=1000, verbose=True,
        hidden_layer_sizes=(14), random_state=1)

import time
start = time.time()
clf.fit(X_train, y_train)
end = time.time()
print("training time: ",end - start)

#prediksi  data test
result = clf.predict(X_test)
# Cek kemampuan kecerdasan buatan dengan data uji 
test_accuracy = clf.score(X_test, y_test)
print('Akurasi Data Uji:', test_accuracy)

print('Hasil Prediksi : ')
print(result)

print('Nilai Target seharusnya : ')
print(y_test)

training time:  0.239013671875


In [19]:
clf.loss_

2.8991846226024757e-05

In [20]:
#Atribut MLP

print('Loss Pelatihan : ')
print(clf.loss_)    

print('Jumlah Iterasi : ')
print(clf.n_iter_)

print('label output : ')
print(clf.classes_)

print('Jumlah output : ')
print(clf.n_outputs_)

print('jenis aktivasi ke output : ')
print(clf.out_activation_)

print('jumlah layers: ')
print(clf.n_layers_)

Loss Pelatihan : 
2.8991846226024757e-05
Jumlah Iterasi : 
19
label output : 
[1. 2. 3. 4. 5.]
Jumlah output : 
5
jenis aktivasi ke output : 
softmax
jumlah layers: 
3


In [21]:
"""# Lakukan proses cross-validation untuk mengetahui seberapa konsisten kemampuan kecerdasan buatan dengan data latih
# yang berbeda-beda subset nya. Dalam contoh ini dilakukan 10 kali cross-validation
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=clf, X=X_train, y=y_train, cv=5)
print(accuracies)

# Catat rerata akurasi dan standar deviasi 10 percobaan pelatihan
avg_accuracy = accuracies.mean()

std_accuracy = accuracies.std()
print('Akurasi: ', avg_accuracy)
print('SD: ', std_accuracy)"""

"# Lakukan proses cross-validation untuk mengetahui seberapa konsisten kemampuan kecerdasan buatan dengan data latih\n# yang berbeda-beda subset nya. Dalam contoh ini dilakukan 10 kali cross-validation\nfrom sklearn.model_selection import cross_val_score\naccuracies = cross_val_score(estimator=clf, X=X_train, y=y_train, cv=5)\nprint(accuracies)\n\n# Catat rerata akurasi dan standar deviasi 10 percobaan pelatihan\navg_accuracy = accuracies.mean()\n\nstd_accuracy = accuracies.std()\nprint('Akurasi: ', avg_accuracy)\nprint('SD: ', std_accuracy)"

In [22]:
#prediksi  data test
result = clf.predict(X_test)
# Cek kemampuan kecerdasan buatan dengan data uji 
test_accuracy = clf.score(X_test, y_test)
print('Akurasi Data Uji:', test_accuracy)

print('Hasil Prediksi : ')
print(result)

print('Nilai Target seharusnya : ')
print(y_test)

Akurasi Data Uji: 0.9411764705882353
Hasil Prediksi : 
[5. 3. 5. 3. 5. 3. 1. 1. 3. 5. 3. 4. 5. 3. 3. 3. 3. 4. 5. 4. 5. 5. 5. 5.
 3. 5. 1. 5. 5. 1. 1. 5. 5. 1. 3. 1. 1. 3. 4. 1. 5. 5. 5. 1. 3. 5. 1. 5.
 1. 3. 4.]
Nilai Target seharusnya : 
[5. 3. 5. 3. 5. 3. 1. 1. 3. 5. 3. 4. 5. 5. 3. 2. 3. 4. 5. 4. 5. 5. 5. 5.
 3. 5. 1. 5. 5. 1. 1. 5. 5. 1. 3. 2. 1. 3. 4. 1. 5. 5. 5. 1. 3. 5. 1. 5.
 1. 3. 4.]


In [23]:
#Confusion Matriks Hasil Prediksi dengan Nilai Sebenarnya
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,result))

[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 12  0  0]
 [ 0  0  0  5  0]
 [ 0  0  1  0 20]]


In [24]:
k=0
sum=0
while k < len(result):
    min=y_test[k]-result[k]
    power=min*min
    sum=sum+power
    mean=sum/(k+1.0)
    root=mean**(1/2.0)
    k=k+1
    print(root)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.5345224838248488
0.5163977794943222
0.5590169943749475
0.5423261445466404
0.5270462766947299
0.512989176042577
0.5
0.4879500364742666
0.4767312946227962
0.4662524041201569
0.45643546458763845
0.4472135954999579
0.4385290096535146
0.4303314829119352
0.4225771273642583
0.41522739926869984
0.408248290463863
0.4016096644512494
0.39528470752104744
0.3892494720807615
0.3834824944236852
0.3779644730092272
0.408248290463863
0.4026936331284146
0.39735970711951313
0.3922322702763681
0.3872983346207417
0.38254602783800296
0.3779644730092272
0.3735436838188142
0.3692744729379982
0.3651483716701107
0.3611575592573076
0.3572948005052482
0.3535533905932738
0.3499271061118826
0.34641016151377546
0.3429971702850177


In [25]:
from sklearn.metrics import mean_squared_error, r2_score
print(mean_squared_error(y_test, result))
print(r2_score(y_test, result))

0.11764705882352941
0.9518565135305224


In [26]:
print(classification_report(y_test,result))

             precision    recall  f1-score   support

        1.0       0.92      1.00      0.96        11
        2.0       0.00      0.00      0.00         2
        3.0       0.86      1.00      0.92        12
        4.0       1.00      1.00      1.00         5
        5.0       1.00      0.95      0.98        21

avg / total       0.91      0.94      0.92        51



D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [28]:
#Uji dengan data latih
result = clf.predict(X_train)
print('Hasil Prediksi : ')
print(result)

from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,result))

Hasil Prediksi : 
[5. 5. 5. 1. 4. 5. 4. 5. 5. 1. 5. 5. 1. 3. 3. 1. 3. 5. 4. 2. 1. 3. 5. 5.
 4. 5. 5. 5. 3. 5. 5. 3. 5. 5. 3. 2. 2. 3. 1. 5. 1. 5. 1. 1. 3. 3. 3. 1.
 5. 5. 1. 3. 3. 3. 5. 1. 5. 5. 1. 1. 4. 5. 2. 1. 5. 1. 3. 1. 5. 3. 1. 5.
 5. 5. 1. 5. 1. 5. 1. 1. 3. 5. 5. 1. 1. 5. 1. 5. 5. 5. 1. 5. 1. 5. 3. 3.
 5. 5. 5. 3. 3. 1. 3. 5. 5. 1. 3. 5. 4. 3. 4. 1. 1. 1. 5. 3. 5. 2.]
[[32  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0 25  0  0]
 [ 0  0  0  7  0]
 [ 0  0  0  0 49]]


In [22]:
#Banyak bobot yang digunakan
print([coef.shape for coef in clf.coefs_])
print("weights between input and first hidden layer:")
print(clf.coefs_[0])
print("\nweights between first hidden and second hidden layer:")
print(clf.coefs_[1])
print("Bias values for first hidden layer:")
print(clf.intercepts_[0])
print("\nBias values for second hidden layer:")
print(clf.intercepts_[1])

[(25, 22), (22, 5)]
weights between input and first hidden layer:
[[ 1.14629625e-01 -9.50344143e-02 -6.38247866e-01 -2.31036044e-01
  -4.31987902e-02  5.27108184e-02 -2.40287754e-01 -3.60309520e-01
   7.46360047e-02 -1.08250962e-01 -4.21108897e-01  2.65642033e-01
  -3.68266243e-01  2.25092052e-01 -6.46899963e-01 -4.29427124e-02
   6.65967341e-02 -7.22222502e-02 -3.64321435e-01 -7.68065452e-01
   1.15192602e-01  2.05298551e-01]
 [-9.08159699e-02  4.23026481e-01  1.96364801e-01  7.58305147e-02
  -5.58215344e-01 -4.62064096e-01 -4.72390853e-01  1.49484092e-01
  -8.79946258e-02 -2.04002319e-01  1.53887190e-01 -4.97085556e-02
  -1.28955627e-01 -2.93728477e-01  1.15821492e-01  4.83700726e-01
  -2.09197931e-02  1.46117380e-01  6.64044506e-01  5.92269490e-01
   2.18848173e-02  4.01247698e-01]
 [-4.70330019e-01  7.52078499e-02  5.09392737e-01  2.73873125e-02
  -3.55350959e-01 -2.03461529e-01 -2.67570146e-01  3.27745453e-01
  -3.54290978e-01 -5.26825914e-02  2.26500468e-01 -5.17099363e-01
   2.4

In [23]:
prob_results = clf.predict_proba(X_test)
print(prob_results)

[[1.06760252e-04 2.73842853e-05 1.87335928e-04 8.04087468e-05
  9.99598111e-01]
 [6.44726372e-04 3.27353084e-04 9.94107518e-01 6.24137071e-04
  4.29626534e-03]
 [1.44040780e-06 1.32252122e-06 4.01883247e-06 2.58573514e-06
  9.99990633e-01]
 [1.67432864e-04 6.19831935e-04 9.98851610e-01 1.95544703e-04
  1.65580614e-04]
 [1.51573662e-03 5.47594411e-03 7.00755410e-02 1.26914581e-02
  9.10241320e-01]
 [9.30123618e-03 3.50116447e-02 3.28761057e-01 3.14916730e-01
  3.12009332e-01]
 [9.62891605e-01 2.67406205e-02 9.42857830e-03 7.65244955e-04
  1.73951077e-04]
 [9.99483247e-01 2.57386596e-04 2.54560861e-04 1.50001000e-06
  3.30553530e-06]
 [4.48459730e-02 1.11085493e-02 1.61000795e-01 7.67954163e-03
  7.75365141e-01]
 [5.51367600e-05 2.23846631e-05 1.84495648e-04 3.51977848e-05
  9.99702785e-01]
 [6.04281353e-03 2.65390397e-03 4.98826440e-01 6.20563272e-03
  4.86271210e-01]
 [4.24201448e-02 1.08952022e-01 3.21504198e-01 5.24227129e-01
  2.89650574e-03]
 [3.58131535e-03 1.20412867e-02 1.521385

In [73]:
#save data ke csv
np.savetxt("Data Latih.csv", X_train, delimiter=",")
np.savetxt("Target Latih.csv", y_train, delimiter=",")

In [75]:
#save data ke csv
np.savetxt("Data Uji.csv", X_test, delimiter=",")
np.savetxt("Target Uji.csv", y_test, delimiter=",")