In [1]:
"""
Created on Tue April 14 20:29:27 2018
@author: hfauzy
"""

#import dataset dari xlsx
import pandas as pd
import numpy as np
#df = pd.read_excel('Urut-Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0)
TrainX = pd.read_csv('Xtrain29.csv', header=None)
Trainy = pd.read_csv('Ytrain29.csv', header=None)
TestX = pd.read_csv('Xtest29.csv', header=None)
Testy = pd.read_csv('Ytest29.csv', header=None)

import numpy as np
#dataset = np.array(df)
X_train=np.array(TrainX)
y_train=np.array(Trainy)
X_test=np.array(TestX)
y_test=np.array(Testy)

y_test=np.ravel(y_test)

y_train=np.ravel(y_train)
'''
#ubah dataframe menjadi array
import numpy as np
dataset = np.array(df)


#membuat dataset target y
y= np.array(dataset)[:,0]
#membuat dataset input X
X = np.array(dataset)[:,1:26]

# Pisahkan dataset menjadi data latih dan uji dengan perbandingan 70:30
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=0)
'''

# Penyekalaan fitur dilakukan pada data latih dan uji.
# Detail kenapa ini penting dijelaskan di sini: http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

# Fungsi fit_transform hanya dilakukan di data latih
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Latih kecerdasan buatan dengan data latih, menggunakan MLP-NN
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(activation='tanh',solver='adam',max_iter=2000,
hidden_layer_sizes=(17), random_state=1)
clf.fit(X_train, y_train)

#Atribut pelatihan MLP
print('Loss Pelatihan : ', end='')
print(clf.loss_)
print('Jumlah Iterasi : ', end='')
print(clf.n_iter_)
print('label output : ', end='')
print(clf.classes_)
print('Jumlah output : ', end='')
print(clf.n_outputs_)
print('jenis aktivasi ke output : ', end='')
print(clf.out_activation_)
print('jumlah layers: ', end='')
print(clf.n_layers_)

'''
#Evaluasi melalui nilai CV
from sklearn.model_selection import cross_val_score
scoring='accuracy'
accuracies = cross_val_score(estimator=clf, X=X_train, y=y_train, cv=5,scoring=scoring)
avg_accuracy = accuracies.mean()
std_accuracy = accuracies.std()
print('Akurasi CV: ', avg_accuracy)
print('SD CV: ', std_accuracy)
'''

#prediksi data test
result = clf.predict(X_test)

# Cek kemampuan kecerdasan buatan dengan data uji
test_accuracy = clf.score(X_test, y_test)
print('Akurasi Data Uji:', test_accuracy)
print('Hasil Prediksi : ', result)
print('Nilai Target seharusnya : ', y_test) 


                                                    
#Confusion Matriks dan Classification Report Hasil Prediksi dengan Nilai Sebenarnya
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,result))
print(classification_report(y_test,result))

#Menampilkan nilai bobot yang digunakan
print([coef.shape for coef in clf.coefs_])
print("weights between input and first hidden layer:")
print(clf.coefs_[0])
print("\nweights between first hidden and second hidden layer:")
print(clf.coefs_[1])
print("Bias values for first hidden layer:")
print(clf.intercepts_[0])
print("\nBias values for second hidden layer:")
print(clf.intercepts_[1])
'''
#menampilkan prediksi estimator
prob_results = clf.predict_proba(X_test)
print(prob_results)

#save data ke csv
np.savetxt("Data Uji.csv", X_test, delimiter=",")
np.savetxt("Hasil Prediksi.csv", result, delimiter=",")
'''

Loss Pelatihan : 0.0382342775759
Jumlah Iterasi : 728
label output : [ 1.  3.  4.  5.]
Jumlah output : 4
jenis aktivasi ke output : softmax
jumlah layers: 3
Akurasi Data Uji: 0.979591836735
Hasil Prediksi :  [ 5.  3.  5.  3.  5.  3.  1.  1.  3.  5.  3.  4.  5.  3.  3.  3.  4.  5.
  4.  5.  5.  5.  5.  3.  5.  1.  5.  5.  1.  1.  5.  5.  1.  3.  1.  3.
  4.  1.  5.  5.  5.  1.  3.  5.  1.  5.  1.  3.  4.]
Nilai Target seharusnya :  [ 5.  3.  5.  3.  5.  3.  1.  1.  3.  5.  3.  4.  5.  5.  3.  3.  4.  5.
  4.  5.  5.  5.  5.  3.  5.  1.  5.  5.  1.  1.  5.  5.  1.  3.  1.  3.
  4.  1.  5.  5.  5.  1.  3.  5.  1.  5.  1.  3.  4.]
[[11  0  0  0]
 [ 0 12  0  0]
 [ 0  0  5  0]
 [ 0  1  0 20]]
             precision    recall  f1-score   support

        1.0       1.00      1.00      1.00        11
        3.0       0.92      1.00      0.96        12
        4.0       1.00      1.00      1.00         5
        5.0       1.00      0.95      0.98        21

avg / total       0.98      0.98     

'\n#menampilkan prediksi estimator\nprob_results = clf.predict_proba(X_test)\nprint(prob_results)\n\n#save data ke csv\nnp.savetxt("Data Uji.csv", X_test, delimiter=",")\nnp.savetxt("Hasil Prediksi.csv", result, delimiter=",")\n'