In [1]:
''' 
jika ingin melakukan eliminasi grup, maka set tujuan = 1
jika ingin melakukan pencarian kombinasi, maka set tujuan = 2

jika menggunakan optimizer adam, set metode = 'a' -> adam
jika menggunakan optimizer lbfgs, set metode = 'b' -> (l) bfgs

'''
tujuan = 1
metode = 'a'

In [2]:
import pandas as pd
import numpy as np
df = pd.read_excel('Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0, sheet_name="Data Fitur Citra Sel Darah2")

In [3]:
#eliminasi per grup
if (tujuan == 1):
    k1 = [ 'Luas_Inti','Keliling_Inti']
    k2 = ['Granularity_Inti','GranularityP']
    k3 = ['Circularity_Inti','CircularityP','Eccentricity']
    k4 = ['RerataR_Inti','RerataG_Inti','RerataB_Inti']
    k5 = ['Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti']
    k6 = ['LuasP','KelilingP']
    k7 = ['RerataRP','RerataGP','RerataBP']
    k8 = ['SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
    k9 = ['LuasNormal_P','KelilingNormal_I']
    k10 =[ 'LIperLP ','KIperKP']

    datset = [k1,k2,k3,k4,k5,k6,k7,k8,k9,k10]



In [4]:
if (tujuan==2):
    if(metode=='a'):
        #pencarian kombinasi
        k7 = ['Jenis','RerataRP','RerataGP','RerataBP']
        k3 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity']
        k5 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti']
        k10 =['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP']
        k8 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
        k9 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','LuasNormal_P','KelilingNormal_I']
        k4 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','LuasNormal_P','KelilingNormal_I','RerataR_Inti','RerataG_Inti','RerataB_Inti']
        k2 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','LuasNormal_P','KelilingNormal_I','RerataR_Inti','RerataG_Inti','RerataB_Inti','Granularity_Inti','GranularityP']
        k6 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','LuasNormal_P','KelilingNormal_I','RerataR_Inti','RerataG_Inti','RerataB_Inti','Granularity_Inti','GranularityP','LuasP','KelilingP']
        k1 =['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','LuasNormal_P','KelilingNormal_I','RerataR_Inti','RerataG_Inti','RerataB_Inti','Granularity_Inti','GranularityP','LuasP','KelilingP', 'Luas_Inti','Keliling_Inti']

        datset = [k7,k3,k5,k10,k8,k9,k4,k2,k6,k1]

    elif (metode=='b'):
        #lbfgs finish
        k2 = ['Jenis','Granularity_Inti','GranularityP']
        k8 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
        k10 =['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP']
        k7 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP']
        k4 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti']
        k9 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I']
        k3 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity']
        k1 = [ 'Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity','Luas_Inti','Keliling_Inti']
        k6 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity','Luas_Inti','Keliling_Inti','LuasP','KelilingP']
        k5 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity','Luas_Inti','Keliling_Inti','LuasP','KelilingP','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti']

        datset = [k2, k8, k10, k7, k4, k9, k3, k1, k6, k5]

In [5]:
data = [ ]
layers = [ ]
loss = [ ]
iterasi = [ ]
cv_score = [ ]
std_cv = [ ]
for i in range(10):
    print(i)
    daf = pd.read_excel('Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0, sheet_name ='Data Fitur Citra Sel Darah2')
    
    if (tujuan==1):
        df = daf.drop(datset[i], axis=1)
    elif (tujuan==2):
        df = daf[datset[i]]
    print(df[0:0])

    import numpy as np
    y= np.array(df)[:,0]           #membuat dataset target y
    X = np.array(df)[:,1:30]    #membuat dataset input X

    # Pisahkan dataset menjadi data latih dan uji dengan perbandingan 80:20
    from sklearn.cross_validation import train_test_split
    X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=0)

    # Penyekalaan fitur dilakukan pada data latih dan uji.
    # Detail kenapa ini penting dijelaskan di sini: http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()

    # Fungsi fit_transform hanya dilakukan di data latih
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)

    # Latih kecerdasan buatan dengan data latih, menggunakan MLP-NN
    from sklearn.neural_network import MLPClassifier
    import time

    if(metode=='a'):
        clf = MLPClassifier(activation='tanh',solver='adam', alpha=1e-5, max_iter=2000,
                hidden_layer_sizes=(28), random_state=1)
    elif (metode=='b'):
        clf = MLPClassifier(activation='relu',solver='lbfgs', alpha=1e-5, max_iter=2000,
                hidden_layer_sizes=(16), random_state=1)
    start = time.time()
    print(clf.fit(X_train, y_train))
    end = time.time()
    waktuTrain = end - start

    from sklearn.model_selection import cross_val_score
    scoring='accuracy'
    accuracies = cross_val_score(estimator=clf, X=X_train, y=y_train, cv=5,scoring=scoring)
    avg_accuracy = float('{0:.4f}'.format(accuracies.mean()))*100
    std_accuracy =  float('{0:.4f}'.format(accuracies.std()))*100
    print('Akurasi: ', avg_accuracy)
    print('SD: ', std_accuracy)

    #prediksi
    start = time.time()
    result = clf.predict(X_test)
    end = time.time()
    waktuTest = end - start

    #Confusion Matriks Hasil Prediksi dengan Nilai Sebenarnya
    from sklearn.metrics import classification_report,confusion_matrix, roc_auc_score
    print(confusion_matrix(y_test,result))

    # Cek kemampuan kecerdasan buatan dengan data uji 
    train_accuracy = float('{0:.4f}'.format(clf.score(X_train, y_train)))*100
    print("akurasi latih: ",train_accuracy)

    # Cek kemampuan kecerdasan buatan dengan data uji 
    test_accuracy = float('{0:.4f}'.format(clf.score(X_test, y_test)))*100
    print("akurasi uji: ",test_accuracy)

    layers.append(i)
    data.append( test_accuracy)
    loss.append(clf.loss_)
    iterasi.append(clf.n_iter_)
    cv_score.append(avg_accuracy)
    std_cv.append(std_accuracy)
    print()


0
Empty DataFrame
Columns: [Jenis, Solidity_Inti, Granularity_Inti, Circularity_Inti, RerataR_Inti, RerataG_Inti, RerataB_Inti, Entropi_Inti, Energi_Inti, Kontras_Inti, Homogenitas_Inti, LuasP, KelilingP, SolidityP, GranularityP, CircularityP, RerataRP, RerataGP, RerataBP, EntropiP, EnergiP, KontrasP, HomogenitasP, LuasNormal_P, KelilingNormal_I, Eccentricity, LIperLP , KIperKP]
Index: []

[0 rows x 28 columns]


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=28, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Akurasi:  93.35
SD:  3.02
[[10  1  0  0  0]
 [ 1  1  0  0  0]
 [ 0  0 12  0  0]
 [ 0  0  0  5  0]
 [ 0  0  1  0 20]]
akurasi latih:  100.0
akurasi uji:  94.12

1
Empty DataFrame
Columns: [Jenis, Luas_Inti, Keliling_Inti, Solidity_Inti, Circularity_Inti, RerataR_Inti, RerataG_Inti, RerataB_Inti, Entropi_Inti, Energi_Inti, Kontras_Inti, Homogenitas_Inti, LuasP, KelilingP, SolidityP, CircularityP, RerataRP, RerataGP, RerataBP, EntropiP, EnergiP, KontrasP, HomogenitasP, LuasNormal_P, KelilingNormal_I, Eccentricity, LIperLP , KIperKP]
Index: []

[0 rows x 28 columns]
MLPC

Akurasi:  94.22
SD:  5.38
[[10  1  0  0  0]
 [ 1  1  0  0  0]
 [ 0  0 11  0  1]
 [ 0  0  1  4  0]
 [ 1  0  1  0 19]]
akurasi latih:  100.0
akurasi uji:  88.24

9
Empty DataFrame
Columns: [Jenis, Luas_Inti, Keliling_Inti, Solidity_Inti, Granularity_Inti, Circularity_Inti, RerataR_Inti, RerataG_Inti, RerataB_Inti, Entropi_Inti, Energi_Inti, Kontras_Inti, Homogenitas_Inti, LuasP, KelilingP, SolidityP, GranularityP, CircularityP, RerataRP, RerataGP, RerataBP, EntropiP, EnergiP, KontrasP, HomogenitasP, LuasNormal_P, KelilingNormal_I, Eccentricity]
Index: []

[0 rows x 28 columns]
MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=28, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_star

In [6]:

i=0
print('elim/komb-Fitur, test acc, loss, iter, cv score, std_cv')
print('-'*40)
while(i<len(layers)):
    print([layers[i],data[i],loss[i], iterasi[i], cv_score[i],std_cv[i]]) 
    i+=1

elim/komb-Fitur, test acc, loss, iter, cv score, std_cv
----------------------------------------
[0, 94.12, 0.029782744832568684, 573, 93.35, 3.02]
[1, 90.2, 0.031532437477985988, 625, 93.53, 7.3999999999999995]
[2, 84.31, 0.035318110767550322, 713, 91.75, 6.63]
[3, 90.2, 0.032593290044555634, 641, 91.82000000000001, 7.06]
[4, 86.27, 0.032167750132433386, 610, 93.46, 5.37]
[5, 92.16, 0.029022708394304465, 556, 92.62, 6.800000000000001]
[6, 82.35, 0.032019939088197627, 578, 93.53, 7.3999999999999995]
[7, 86.27, 0.036253404835299576, 642, 91.82000000000001, 8.309999999999999]
[8, 88.24, 0.03098658422512246, 582, 94.22, 5.38]
[9, 86.27, 0.028152575844042863, 575, 93.42, 5.35]


In [44]:
import pandas as pd
summary = [ ]
i=0
while(i<len(layers)):
    summary.append([layers[i],data[i],loss[i], iterasi[i], cv_score[i],std_cv[i]]) 
    i+=1
    
df = pd.DataFrame(np.array(summary))
df.columns = (['neuron','akurasi','loss','iter','cv','std'])
df

neuron  akurasi      loss    iter     cv   std
0     0.0    82.35  0.248139  2000.0  86.52  5.36
1     1.0    82.35  0.134777  1533.0  86.74  7.68
2     2.0    78.43  0.056072  1026.0  86.74  6.63
3     3.0    78.43  0.052296  1040.0  88.41  6.64
4     4.0    82.35  0.048847   789.0  90.15  9.18
5     5.0    86.27  0.046698   729.0  90.95  7.60
6     6.0    88.24  0.039773   682.0  90.95  7.60
7     7.0    84.31  0.033974   613.0  90.01  5.92
8     8.0    86.27  0.035857   672.0  93.53  7.40
9     9.0    84.31  0.029367   576.0  92.66  6.82