In [1]:
import pandas as pd
import numpy as np
#df = pd.read_excel('Urut-Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0)
df = pd.read_excel('Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0,sheet_name='Data Fitur Citra Sel Darah2')

In [2]:
head = ['Jenis', 'KIperKP', 'KontrasP', 'Solidity_Inti', 'HomogenitasP',
        'Circularity_Inti', 'Keliling_Inti', 'LIperLP ', 'KelilingP',
        'EntropiP', 'LuasNormal_P', 'EnergiP', 'Homogenitas_Inti',
        'KelilingNormal_I', 'Entropi_Inti', 'Granularity_Inti',
        'RerataGP', 'SolidityP', 'Energi_Inti', 'RerataRP',
        'RerataR_Inti', 'CircularityP', 'LuasP', 'GranularityP',
        'RerataG_Inti', 'RerataBP', 'Eccentricity', 'RerataB_Inti',
        'Kontras_Inti', 'Luas_Inti']

In [3]:
k1 =[ 'Luas_Inti','Keliling_Inti']
k2 = ['Granularity_Inti','GranularityP']
k3 = ['Circularity_Inti','CircularityP','Eccentricity']
k4 = ['RerataR_Inti','RerataG_Inti','RerataB_Inti']
k5 = ['Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti']
k6 = ['LuasP','KelilingP']
k7 = ['RerataRP','RerataGP','RerataBP']
k8 = ['SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
k9 = ['LuasNormal_P','KelilingNormal_I']
k10 =[ 'LIperLP ','KIperKP']

datset = [k1,k2,k3,k4,k5,k6,k7,k8,k9,k10]

#adam
#    1          2         3         4         5          6          7          8           9         10
#[99.15, 99.15, 99.15, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 99.15]
#[88.24, 86.27, 86.27, 88.24, 86.27, 88.24, 88.24, 82.35, 84.31, 86.27]

#lbfgs
#    1          2         3         4         5          6          7          8           9         10
#[100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
#[90.2, 84.31, 82.35, 86.27, 90.2, 88.24, 86.27, 80.39, 88.24, 80.39]

In [4]:
k1 =[ 'Luas_Inti','Keliling_Inti','LuasP','KelilingP','LIperLP ','KIperKP']
k2 = ['Granularity_Inti','GranularityP']
k3 = ['Circularity_Inti','CircularityP','Eccentricity']
k4 = ['RerataR_Inti','RerataG_Inti','RerataB_Inti','RerataRP','RerataGP','RerataBP']
k5 = ['Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
k6 = ['LuasNormal_P','KelilingNormal_I']

datset = [k1,k2,k3,k4,k5,k6]

#adam
#     1         2        3            4          5          6
#[100.0, 99.15, 99.15, 100.0, 99.15, 100.0]
#[84.31, 86.27, 86.27, 84.31, 88.24, 84.31]

#lbfgs
#     1         2        3            4          5          6
#[100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
#[84.31, 84.31, 82.35, 84.31, 86.27, 88.24]


In [4]:
tolen= 0
for i in range(len(datset)):
    tolen = tolen +len(datset[i])
print(tolen)
len(datset)

29


10

In [50]:
#lbfgs finish
k2 = ['Jenis','Granularity_Inti','GranularityP']
k8 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
k10 =['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP']
k7 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP']
k4 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti']
k9 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I']
k3 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity']
k1 =[ 'Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity','Luas_Inti','Keliling_Inti']
k6 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity','Luas_Inti','Keliling_Inti','LuasP','KelilingP']
k5 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity','Luas_Inti','Keliling_Inti','LuasP','KelilingP','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti']

datset = [k2, k8, k10, k7, k4, k9, k3, k1, k6, k5]

In [52]:
#adam finish
k2 = ['Jenis','Granularity_Inti','GranularityP']
k1 =['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti']
k7 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP']
k8 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
k4 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti']
k10 =['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP']
k9 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP','LuasNormal_P','KelilingNormal_I']
k6 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP','LuasNormal_P','KelilingNormal_I','LuasP','KelilingP']
k3 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP','LuasNormal_P','KelilingNormal_I','LuasP','KelilingP','Circularity_Inti','CircularityP','Eccentricity']
k5 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP','LuasNormal_P','KelilingNormal_I','LuasP','KelilingP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti']

datset = [k2, k1, k7, k8, k4, k10, k9, k6, k3, k2]

In [14]:
#Reordering Columns by name
df = pd.read_excel('Urut-Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0)
df = df[k2]
#df

In [12]:
daf = pd.read_excel('Urut-Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0)
#df = daf.drop(datset[0], axis=1)
print(df[0:0])

Empty DataFrame
Columns: [Jenis, KIperKP, KontrasP, Solidity_Inti, HomogenitasP, Circularity_Inti, LIperLP , KelilingP, EntropiP, LuasNormal_P, EnergiP, Homogenitas_Inti, KelilingNormal_I, Entropi_Inti, Granularity_Inti, RerataGP, SolidityP, Energi_Inti, RerataRP, RerataR_Inti, CircularityP, LuasP, GranularityP, RerataG_Inti, RerataBP, Eccentricity, RerataB_Inti, Kontras_Inti]
Index: []

[0 rows x 28 columns]


In [51]:
train = [ ]
test = [ ]
cv_score = [ ]
cv_std = [ ]
for i in range(10):
    print(i)

    daf = pd.read_excel('Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0, sheet_name ='Data Fitur Citra Sel Darah2')
    #df = daf.drop(datset[i], axis=1)
    df = daf[datset[i]]
    print(df[0:0])

    import numpy as np
    y= np.array(df)[:,0]           #membuat dataset target y
    X = np.array(df)[:,1:30]    #membuat dataset input X

    # Pisahkan dataset menjadi data latih dan uji dengan perbandingan 80:20
    from sklearn.cross_validation import train_test_split
    X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=0)

    # Penyekalaan fitur dilakukan pada data latih dan uji.
    # Detail kenapa ini penting dijelaskan di sini: http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()

    # Fungsi fit_transform hanya dilakukan di data latih
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)

    # Latih kecerdasan buatan dengan data latih, menggunakan MLP-NN
    from sklearn.neural_network import MLPClassifier
    import time

    clf = MLPClassifier(activation='tanh',solver='adam', alpha=1e-5, max_iter=2000,
                hidden_layer_sizes=(16), random_state=1)
    start = time.time()
    print(clf.fit(X_train, y_train))
    end = time.time()
    waktuTrain = end - start

    from sklearn.model_selection import cross_val_score
    scoring='accuracy'
    accuracies = cross_val_score(estimator=clf, X=X_train, y=y_train, cv=5,scoring=scoring)
    avg_accuracy = float('{0:.4f}'.format(accuracies.mean()))*100
    std_accuracy =  float('{0:.4f}'.format(accuracies.std()))*100
    print('Akurasi: ', avg_accuracy)
    print('SD: ', std_accuracy)

    #prediksi
    start = time.time()
    result = clf.predict(X_test)
    end = time.time()
    waktuTest = end - start

    #Confusion Matriks Hasil Prediksi dengan Nilai Sebenarnya
    from sklearn.metrics import classification_report,confusion_matrix, roc_auc_score
    print(confusion_matrix(y_test,result))

    # Cek kemampuan kecerdasan buatan dengan data uji 
    train_accuracy = float('{0:.4f}'.format(clf.score(X_train, y_train)))*100
    print("akurasi latih: ",train_accuracy)

    # Cek kemampuan kecerdasan buatan dengan data uji 
    test_accuracy = float('{0:.4f}'.format(clf.score(X_test, y_test)))*100
    print("akurasi uji: ",test_accuracy)

    train.append(train_accuracy)
    cv_score.append(avg_accuracy)
    cv_std.append(std_accuracy)
    test.append(test_accuracy)
    print()


0
Empty DataFrame
Columns: [Jenis, Granularity_Inti, GranularityP]
Index: []
MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=16, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Akurasi:  83.22
SD:  5.36
[[11  0  0  0  0]
 [ 0  0  2  0  0]
 [ 1  0 11  0  0]
 [ 3  1  1  0  0]
 [ 1  0  4  0 16]]
akurasi latih:  84.75
akurasi uji:  74.51

1
Empty DataFrame
Columns: [Jenis, Granularity_Inti, GranularityP, SolidityP, EntropiP, EnergiP, KontrasP, HomogenitasP]
Index: []
MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=16, learning_rate='constant',
       learnin

D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Akurasi:  87.36
SD:  5.029999999999999
[[10  1  0  0  0]
 [ 0  2  0  0  0]
 [ 1  0 11  0  0]
 [ 1  1  0  3  0]
 [ 1  0  3  1 16]]
akurasi latih:  91.53
akurasi uji:  82.35

2
Empty DataFrame
Columns: [Jenis, Granularity_Inti, GranularityP, SolidityP, EntropiP, EnergiP, KontrasP, HomogenitasP, LIperLP , KIperKP]
Index: []
MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=16, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Akurasi:  88.34
SD:  7.779999999999999
[[11  0  0  0  0]
 [ 1  1  0  0  0]
 [ 0  0 12  0  0]
 [ 0  1  0  4  0]
 [ 1  0  2  1 17]]
akurasi latih:  95.76
akurasi uji:  88.24

3
Empty DataFrame
Columns: [Jenis, Granularity_Inti, GranularityP, SolidityP,

In [48]:
accuracies

array([0.76      , 0.8       , 0.86956522, 0.91304348, 0.81818182])

In [40]:
train

[84.75, 91.53, 95.76, 98.31, 99.15, 99.15, 100.0, 100.0, 99.15, 100.0]

In [41]:
cv_score

[83.22,
 87.36,
 88.34,
 89.25,
 90.88000000000001,
 90.99000000000001,
 91.86,
 92.66,
 92.66,
 94.33]

In [42]:
cv_std

[5.36,
 5.029999999999999,
 7.779999999999999,
 8.76,
 5.72,
 8.110000000000001,
 8.33,
 6.819999999999999,
 6.819999999999999,
 7.41]

In [49]:
test

[74.51, 78.43, 80.39, 84.31, 88.24, 90.2, 88.24, 86.27, 84.31, 74.51]

In [ ]:
#lbfgs
#    1          2         3         4         5          6          7          8           9         10
#[100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
#[90.2, 84.31, 82.35, 86.27, 90.2, 88.24, 86.27, 80.39, 88.24, 80.39]

#lbfgs
#     1         2        3            4          5          6
#[100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
#[84.31, 84.31, 82.35, 84.31, 86.27, 88.24]


In [25]:
df = pd.read_excel('Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0,sheet_name='Data Fitur Citra Sel Darah2')
#df = daf.drop(datset[i], axis=1)
df = df[Jenis, k1]
print(df[0:0])

import numpy as np
y= np.array(df)[:,0]           #membuat dataset target y
X = np.array(df)[:,1:30]    #membuat dataset input X

# Pisahkan dataset menjadi data latih dan uji dengan perbandingan 80:20
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=0)

# Penyekalaan fitur dilakukan pada data latih dan uji.
# Detail kenapa ini penting dijelaskan di sini: http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

# Fungsi fit_transform hanya dilakukan di data latih
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Empty DataFrame
Columns: [Jenis, Luas_Inti, Keliling_Inti, Solidity_Inti, Granularity_Inti, Circularity_Inti, RerataR_Inti, RerataG_Inti, RerataB_Inti, Entropi_Inti, Energi_Inti, Kontras_Inti, Homogenitas_Inti, LuasP, KelilingP, SolidityP, GranularityP, CircularityP, RerataRP, RerataGP, RerataBP, EntropiP, EnergiP, KontrasP, HomogenitasP, LuasNormal_P, KelilingNormal_I, Eccentricity, LIperLP , KIperKP]
Index: []

[0 rows x 30 columns]


In [50]:
#lbfgs finish
k2 = ['Jenis','Granularity_Inti','GranularityP']
k8 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
k10 =['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP']
k7 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP']
k4 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti']
k9 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I']
k3 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity']
k1 =[ 'Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity','Luas_Inti','Keliling_Inti']
k6 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity','Luas_Inti','Keliling_Inti','LuasP','KelilingP']
k5 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity','Luas_Inti','Keliling_Inti','LuasP','KelilingP','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti']

datset = [k2, k8, k10, k7, k4, k9, k3, k1, k6, k5]

In [53]:
# Latih kecerdasan buatan dengan data latih, menggunakan MLP-NN
df = pd.read_excel('Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0, sheet_name ='Data Fitur Citra Sel Darah2')
#df = daf.drop(datset[i], axis=1)
df = df[datset[5]]
print(df[0:0])

from sklearn.neural_network import MLPClassifier

i=10
data = [ ]
layers = [ ]
loss = [ ]
iterasi = [ ]
cv_score = [ ]
std_cv = [ ]
while (i<75):
    clf = MLPClassifier(activation='tanh',solver='adam', alpha=1e-5, max_iter=2000,
                    hidden_layer_sizes=(i), random_state=1)
    print(clf.fit(X_train, y_train))
    if(i>=30):
        i=i+5
    elif(i<30):  
        i=i+1

    print('Loss Pelatihan : ', clf.loss_)    
    print('Jumlah iterasi : ', clf.n_iter_)
    
    from sklearn.model_selection import cross_val_score
    scoring='accuracy'
    accuracies = cross_val_score(estimator=clf, X=X_train, y=y_train, cv=10,scoring=scoring)
    avg_accuracy = float('{0:.4f}'.format(accuracies.mean()))*100
    std_accuracy =  float('{0:.4f}'.format(accuracies.std()))*100
    print('Akurasi: ', avg_accuracy)
    print('SD: ', std_accuracy)
    
    #Prediksi Data Uji
    result = clf.predict(X_test)

    #Confusion Matriks Hasil Prediksi dengan Nilai Sebenarnya
    from sklearn.metrics import classification_report,confusion_matrix
    print(confusion_matrix(y_test,result))

    # Cek kemampuan kecerdasan buatan dengan data uji 
    test_accuracy = clf.score(X_test, y_test)
    from sklearn.metrics import accuracy_score
    akurasi = accuracy_score(y_test, result)
    print('Akurasi Data Uji:', test_accuracy , '=', akurasi)

    # Cek kemampuan kecerdasan buatan dengan data uji 
    train_accuracy = clf.score(X_train, y_train)
    print('Akurasi Data Latih:', train_accuracy)  

    layers.append(i)
    data.append( float('{0:.4f}'.format(test_accuracy))*100)
    loss.append(clf.loss_)
    iterasi.append(clf.n_iter_)
    cv_score.append(avg_accuracy)
    std_cv.append(std_accuracy)
    print()

Empty DataFrame
Columns: [Jenis, Granularity_Inti, GranularityP, Luas_Inti, Keliling_Inti, RerataRP, RerataGP, RerataBP, SolidityP, EntropiP, EnergiP, KontrasP, HomogenitasP, RerataR_Inti, RerataG_Inti, RerataB_Inti, LIperLP , KIperKP]
Index: []
MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=10, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.05518116167689407
Jumlah iterasi :  992


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  91.3
SD:  5.91
[[ 9  2  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 10  0  2]
 [ 0  1  0  4  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.8431372549019608 = 0.8431372549019608
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=11, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.050786451086012964
Jumlah iterasi :  927


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  92.02
SD:  4.62
[[ 9  1  0  0  1]
 [ 1  0  1  0  0]
 [ 0  0 11  0  1]
 [ 0  0  0  5  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.8823529411764706 = 0.8823529411764706
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=12, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.04482444467041813
Jumlah iterasi :  849


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  90.53
SD:  7.109999999999999
[[10  1  0  0  0]
 [ 1  1  0  0  0]
 [ 0  0 10  0  2]
 [ 0  0  1  4  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.8823529411764706 = 0.8823529411764706
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=13, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.049271955418239755
Jumlah iterasi :  814


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  92.02
SD:  4.62
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 11  0  1]
 [ 0  1  1  3  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.8823529411764706 = 0.8823529411764706
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=14, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.04236717114824548
Jumlah iterasi :  795


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  92.07
SD:  6.47
[[10  1  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 11  0  1]
 [ 0  1  0  4  0]
 [ 1  0  1  0 19]]
Akurasi Data Uji: 0.8627450980392157 = 0.8627450980392157
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=15, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.03458000455700401
Jumlah iterasi :  633


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  92.78999999999999
SD:  5.21
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 11  0  1]
 [ 0  1  0  4  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.9019607843137255 = 0.9019607843137255
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=16, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.04305189063482356
Jumlah iterasi :  845


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  92.78999999999999
SD:  6.11
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 11  0  1]
 [ 0  1  0  4  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.9019607843137255 = 0.9019607843137255
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=17, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.04275985492821209
Jumlah iterasi :  768


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  93.17999999999999
SD:  8.19
[[10  1  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 11  0  1]
 [ 0  1  1  3  0]
 [ 1  0  1  0 19]]
Akurasi Data Uji: 0.8431372549019608 = 0.8431372549019608
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=18, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.03674658625776479
Jumlah iterasi :  682


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  92.97999999999999
SD:  6.87
[[11  0  0  0  0]
 [ 1  1  0  0  0]
 [ 0  0 11  0  1]
 [ 0  2  0  3  0]
 [ 1  0  1  0 19]]
Akurasi Data Uji: 0.8823529411764706 = 0.8823529411764706
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=19, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.04138048922281854
Jumlah iterasi :  744


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  90.73
SD:  8.36
[[10  1  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 11  0  1]
 [ 0  1  0  4  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.8823529411764706 = 0.8823529411764706
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=20, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.04068607726835477
Jumlah iterasi :  713


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  92.93
SD:  6.21
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 10  0  2]
 [ 0  1  1  3  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.8627450980392157 = 0.8627450980392157
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=21, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.03692079462482234
Jumlah iterasi :  728


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  92.97999999999999
SD:  6.87
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 10  0  2]
 [ 0  1  0  4  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.8823529411764706 = 0.8823529411764706
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=22, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.03758332066282276
Jumlah iterasi :  658


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  93.7
SD:  5.58
[[10  1  0  0  0]
 [ 1  1  0  0  0]
 [ 0  0 10  0  2]
 [ 0  1  0  4  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.8823529411764706 = 0.8823529411764706
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=23, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.035737574996982595
Jumlah iterasi :  654


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  94.75
SD:  7.28
[[10  1  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 11  0  1]
 [ 0  0  1  4  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.8823529411764706 = 0.8823529411764706
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=24, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.03768156124127872
Jumlah iterasi :  679


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  92.78999999999999
SD:  5.21
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0  8  0  4]
 [ 0  0  1  4  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.8431372549019608 = 0.8431372549019608
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=25, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.03416664154153711
Jumlah iterasi :  675


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  93.17999999999999
SD:  8.19
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 11  0  1]
 [ 0  0  1  4  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.9019607843137255 = 0.9019607843137255
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=26, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.03442272820247523
Jumlah iterasi :  658


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  94.6
SD:  5.79
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 11  0  1]
 [ 1  0  0  4  0]
 [ 1  0  1  0 19]]
Akurasi Data Uji: 0.8823529411764706 = 0.8823529411764706
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=27, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.03536473012269056
Jumlah iterasi :  623


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  92.93
SD:  5.18
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 10  0  2]
 [ 0  0  0  5  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.9019607843137255 = 0.9019607843137255
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=28, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.03375906905035496
Jumlah iterasi :  640


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  94.69999999999999
SD:  6.5600000000000005
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 10  0  2]
 [ 0  1  0  4  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.8823529411764706 = 0.8823529411764706
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=29, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.03438403426817519
Jumlah iterasi :  615


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  95.66
SD:  7.31
[[11  0  0  0  0]
 [ 1  1  0  0  0]
 [ 0  0 10  0  2]
 [ 1  0  2  2  0]
 [ 1  0  1  0 19]]
Akurasi Data Uji: 0.8431372549019608 = 0.8431372549019608
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=30, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.0350717589743639
Jumlah iterasi :  639


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  94.6
SD:  5.79
[[10  1  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 10  0  2]
 [ 0  1  0  4  0]
 [ 1  0  1  0 19]]
Akurasi Data Uji: 0.8431372549019608 = 0.8431372549019608
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=35, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.026698888794486814
Jumlah iterasi :  510


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  94.84
SD:  6.61
[[11  0  0  0  0]
 [ 1  1  0  0  0]
 [ 0  0 11  0  1]
 [ 0  0  0  5  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.9411764705882353 = 0.9411764705882353
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=40, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.02860779759560287
Jumlah iterasi :  533


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  93.7
SD:  5.58
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 10  0  2]
 [ 0  0  2  3  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.8627450980392157 = 0.8627450980392157
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=45, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.03129959315621005
Jumlah iterasi :  624


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  92.97999999999999
SD:  6.87
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 11  0  1]
 [ 0  1  0  4  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.9019607843137255 = 0.9019607843137255
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=50, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.024070807829184086
Jumlah iterasi :  486


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  94.41000000000001
SD:  4.9399999999999995
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 10  0  2]
 [ 0  1  1  3  0]
 [ 1  0  1  0 19]]
Akurasi Data Uji: 0.8431372549019608 = 0.8431372549019608
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=55, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.024912584503754952
Jumlah iterasi :  496


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  94.41000000000001
SD:  4.9399999999999995
[[ 8  2  0  0  1]
 [ 1  0  1  0  0]
 [ 0  0 10  0  2]
 [ 0  0  1  4  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.8235294117647058 = 0.8235294117647058
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=60, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.023311743577598715
Jumlah iterasi :  488


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  95.17999999999999
SD:  5.140000000000001
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 11  0  1]
 [ 0  0  0  5  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.9215686274509803 = 0.9215686274509803
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=65, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.02124719937518302
Jumlah iterasi :  423


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  93.5
SD:  4.65
[[10  1  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 11  0  1]
 [ 0  1  1  3  0]
 [ 1  0  1  0 19]]
Akurasi Data Uji: 0.8431372549019608 = 0.8431372549019608
Akurasi Data Latih: 1.0

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=70, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.020041617152196087
Jumlah iterasi :  402


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 5 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Akurasi:  94.27
SD:  5.01
[[11  0  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 10  0  2]
 [ 0  1  0  4  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.8823529411764706 = 0.8823529411764706
Akurasi Data Latih: 1.0



In [52]:
#adam finish
k2 = ['Jenis','Granularity_Inti','GranularityP']
k1 =['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti']
k7 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP']
k8 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
k4 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti']
k10 =['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP']
k9 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP','LuasNormal_P','KelilingNormal_I']
k6 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP','LuasNormal_P','KelilingNormal_I','LuasP','KelilingP']
k3 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP','LuasNormal_P','KelilingNormal_I','LuasP','KelilingP','Circularity_Inti','CircularityP','Eccentricity']
k5 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP','LuasNormal_P','KelilingNormal_I','LuasP','KelilingP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti']

datset = [k2, k1, k7, k8, k4, k10, k9, k6, k3, k2]

In [55]:
data

[84.31,
 88.24,
 88.24,
 88.24,
 86.27,
 90.2,
 90.2,
 84.31,
 88.24,
 88.24,
 86.27,
 88.24,
 88.24,
 88.24,
 84.31,
 90.2,
 88.24,
 90.2,
 88.24,
 84.31,
 84.31,
 94.12,
 86.27,
 90.2,
 84.31,
 82.35,
 92.16,
 84.31,
 88.24]

In [44]:
import pandas as pd
summary = [ ]
i=0
while(i<len(layers)):
    summary.append([layers[i],data[i],loss[i], iterasi[i], cv_score[i],std_cv[i]]) 
    i+=1
    
df = pd.DataFrame(np.array(summary))
df.columns = (['neuron','akurasi','loss','iter','cv','std'])
df

neuron  akurasi      loss  iter     cv   std
0     11.0    80.39  0.000072  20.0  92.79  6.11
1     12.0    86.27  0.000035  18.0  92.98  6.87
2     13.0    86.27  0.000070  18.0  90.20  8.79
3     14.0    86.27  0.000082  19.0  91.25  6.04
4     15.0    86.27  0.000050  18.0  95.60  5.77
5     16.0    84.31  0.000028  20.0  92.98  6.87
6     17.0    86.27  0.000083  20.0  92.73  4.12
7     18.0    86.27  0.000074  18.0  91.05  5.68
8     19.0    84.31  0.000051  19.0  93.02  6.18
9     20.0    86.27  0.000052  19.0  94.41  4.94
10    21.0    84.31  0.000047  18.0  92.98  6.87
11    22.0    84.31  0.000078  17.0  92.79  6.11
12    23.0    78.43  0.000073  17.0  92.93  5.18
13    24.0    80.39  0.000112  17.0  92.93  6.99
14    25.0    86.27  0.000043  20.0  91.64  8.21
15    26.0    84.31  0.000069  17.0  92.98  6.87
16    27.0    82.35  0.000036  17.0  92.07  6.47
17    28.0    82.35  0.000061  17.0  92.02  5.76
18    29.0    90.20  0.000053  17.0  92.98  6.87
19    30.0    86.27  0.000029  18.0  91.44  6.85
20    35.0    84.31  0.000052  17.0  91.30  5.91
21    40.0    86.27  0.000120  15.0  93.64  5.74
22    45.0    86.27  0.000110  16.0  92.79  6.11
23    50.0    90.20  0.000071  17.0  92.02  6.59
24    55.0    86.27  0.000061  17.0  93.70  5.58
25    60.0    82.35  0.000063  16.0  94.46  6.68
26    65.0    84.31  0.000154  15.0  95.37  6.75
27    70.0    82.35  0.000053  18.0  91.25  6.04
28    75.0    88.24  0.000097  15.0  92.84  6.89