In [1]:
import pandas as pd
import numpy as np
#df = pd.read_excel('Urut-Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0)
df = pd.read_excel('Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0,sheet_name='Data Fitur Citra Sel Darah2')

In [2]:
head = ['Jenis', 'KIperKP', 'KontrasP', 'Solidity_Inti', 'HomogenitasP',
        'Circularity_Inti', 'Keliling_Inti', 'LIperLP ', 'KelilingP',
        'EntropiP', 'LuasNormal_P', 'EnergiP', 'Homogenitas_Inti',
        'KelilingNormal_I', 'Entropi_Inti', 'Granularity_Inti',
        'RerataGP', 'SolidityP', 'Energi_Inti', 'RerataRP',
        'RerataR_Inti', 'CircularityP', 'LuasP', 'GranularityP',
        'RerataG_Inti', 'RerataBP', 'Eccentricity', 'RerataB_Inti',
        'Kontras_Inti', 'Luas_Inti']

head = ['Luas_Inti','Keliling_Inti','Solidity_Inti','Granularity_Inti',
        'Circularity_Inti','RerataR_Inti','RerataG_Inti','RerataB_Inti','Entropi_Inti',
        'Energi_Inti','Kontras_Inti','Homogenitas_Inti','LuasP','KelilingP','SolidityP',
        'GranularityP','CircularityP','RerataRP','RerataGP','RerataBP','EntropiP','EnergiP',
        'KontrasP','HomogenitasP','LuasNormal_P','KelilingNormal_I','Eccentricity','LIperLP ','KIperKP']


In [3]:
k1 =[ 'Luas_Inti','Keliling_Inti']
k2 = ['Granularity_Inti','GranularityP']
k3 = ['Circularity_Inti','CircularityP','Eccentricity']
k4 = ['RerataR_Inti','RerataG_Inti','RerataB_Inti']
k5 = ['Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti']
k6 = ['LuasP','KelilingP']
k7 = ['RerataRP','RerataGP','RerataBP']
k8 = ['SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
k9 = ['LuasNormal_P','KelilingNormal_I']
k10 =[ 'LIperLP ','KIperKP']

datset = [k1,k2,k3,k4,k5,k6,k7,k8,k9,k10]

#adam
#    1          2         3         4         5          6          7          8           9         10
#[99.15, 99.15, 99.15, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 99.15]
#[88.24, 86.27, 86.27, 88.24, 86.27, 88.24, 88.24, 82.35, 84.31, 86.27]

#lbfgs
#    1          2         3         4         5          6          7          8           9         10
#[100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
#[90.2, 84.31, 82.35, 86.27, 90.2, 88.24, 86.27, 80.39, 88.24, 80.39]

In [4]:
tolen= 0
for i in range(len(datset)):
    tolen = tolen +len(datset[i])
print(tolen)
len(datset)

29


10

In [ ]:
#adam finish
k2 = ['Jenis','Granularity_Inti','GranularityP']
k1 =['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti']
k7 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP']
k8 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
k4 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti']
k10 =['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP']
k9 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP','LuasNormal_P','KelilingNormal_I']
k6 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP','LuasNormal_P','KelilingNormal_I','LuasP','KelilingP']
k3 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP','LuasNormal_P','KelilingNormal_I','LuasP','KelilingP','Circularity_Inti','CircularityP','Eccentricity']
k5 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP','LuasNormal_P','KelilingNormal_I','LuasP','KelilingP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti']

datset = [k2, k1, k7, k8, k4, k10, k9, k6, k3, k5]

In [ ]:
#Reordering Columns by name
df = pd.read_excel('Urut-Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0)
df = df[k2]
#df

In [ ]:
daf = pd.read_excel('Urut-Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0)
#df = daf.drop(datset[0], axis=1)
print(df[0:0])

In [ ]:

k7 = ['Jenis','RerataRP','RerataGP','RerataBP']
k3 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity']
k5 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti']
k10 =['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP']
k8 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
k9 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','LuasNormal_P','KelilingNormal_I']
k4 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','LuasNormal_P','KelilingNormal_I','RerataR_Inti','RerataG_Inti','RerataB_Inti']
k2 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','LuasNormal_P','KelilingNormal_I','RerataR_Inti','RerataG_Inti','RerataB_Inti','Granularity_Inti','GranularityP']
k6 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','LuasNormal_P','KelilingNormal_I','RerataR_Inti','RerataG_Inti','RerataB_Inti','Granularity_Inti','GranularityP','LuasP','KelilingP']
k1 =['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','LuasNormal_P','KelilingNormal_I','RerataR_Inti','RerataG_Inti','RerataB_Inti','Granularity_Inti','GranularityP','LuasP','KelilingP', 'Luas_Inti','Keliling_Inti']

datset = [k7,k3,k5,k10,k8,k9,k4,k2,k6,k1]

In [5]:
train = [ ]
test = [ ]
cv_score = [ ]
cv_std = [ ]
for i in range(10):
    print(i)

    daf = pd.read_excel('Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0, sheet_name ='Data Fitur Citra Sel Darah2')
    df = daf.drop(datset[i], axis=1)
    #df = daf[datset[i]]
    print(df[0:0])

    import numpy as np
    y= np.array(df)[:,0]           #membuat dataset target y
    X = np.array(df)[:,1:30]    #membuat dataset input X

    # Pisahkan dataset menjadi data latih dan uji dengan perbandingan 80:20
    from sklearn.cross_validation import train_test_split
    X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=0)

    # Penyekalaan fitur dilakukan pada data latih dan uji.
    # Detail kenapa ini penting dijelaskan di sini: http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()

    # Fungsi fit_transform hanya dilakukan di data latih
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)

    # Latih kecerdasan buatan dengan data latih, menggunakan MLP-NN
    from sklearn.neural_network import MLPClassifier
    import time

    clf = MLPClassifier(activation='tanh',solver='adam', alpha=1e-5, max_iter=2000,
                hidden_layer_sizes=(28), random_state=1)
    start = time.time()
    print(clf.fit(X_train, y_train))
    end = time.time()
    waktuTrain = end - start

    from sklearn.model_selection import cross_val_score
    scoring='accuracy'
    accuracies = cross_val_score(estimator=clf, X=X_train, y=y_train, cv=5,scoring=scoring)
    avg_accuracy = float('{0:.4f}'.format(accuracies.mean()))*100
    std_accuracy =  float('{0:.4f}'.format(accuracies.std()))*100
    print('Akurasi: ', avg_accuracy)
    print('SD: ', std_accuracy)

    #prediksi
    start = time.time()
    result = clf.predict(X_test)
    end = time.time()
    waktuTest = end - start

    #Confusion Matriks Hasil Prediksi dengan Nilai Sebenarnya
    from sklearn.metrics import classification_report,confusion_matrix, roc_auc_score
    print(confusion_matrix(y_test,result))

    # Cek kemampuan kecerdasan buatan dengan data uji 
    train_accuracy = float('{0:.4f}'.format(clf.score(X_train, y_train)))*100
    print("akurasi latih: ",train_accuracy)

    # Cek kemampuan kecerdasan buatan dengan data uji 
    test_accuracy = float('{0:.4f}'.format(clf.score(X_test, y_test)))*100
    print("akurasi uji: ",test_accuracy)

    train.append(train_accuracy)
    cv_score.append(avg_accuracy)
    cv_std.append(std_accuracy)
    test.append(test_accuracy)
    print()


0
Empty DataFrame
Columns: [Jenis, Solidity_Inti, Granularity_Inti, Circularity_Inti, RerataR_Inti, RerataG_Inti, RerataB_Inti, Entropi_Inti, Energi_Inti, Kontras_Inti, Homogenitas_Inti, LuasP, KelilingP, SolidityP, GranularityP, CircularityP, RerataRP, RerataGP, RerataBP, EntropiP, EnergiP, KontrasP, HomogenitasP, LuasNormal_P, KelilingNormal_I, Eccentricity, LIperLP , KIperKP]
Index: []

[0 rows x 28 columns]


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=28, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Akurasi:  93.35
SD:  3.02
[[10  1  0  0  0]
 [ 1  1  0  0  0]
 [ 0  0 12  0  0]
 [ 0  0  0  5  0]
 [ 0  0  1  0 20]]
akurasi latih:  100.0
akurasi uji:  94.12

1
Empty DataFrame
Columns: [Jenis, Luas_Inti, Keliling_Inti, Solidity_Inti, Circularity_Inti, RerataR_Inti, RerataG_Inti, RerataB_Inti, Entropi_Inti, Energi_Inti, Kontras_Inti, Homogenitas_Inti, LuasP, KelilingP, SolidityP, CircularityP, RerataRP, RerataGP, RerataBP, EntropiP, EnergiP, KontrasP, HomogenitasP, LuasNormal_P, KelilingNormal_I, Eccentricity, LIperLP , KIperKP]
Index: []

[0 rows x 28 columns]
MLPC

Akurasi:  94.22
SD:  5.38
[[10  1  0  0  0]
 [ 1  1  0  0  0]
 [ 0  0 11  0  1]
 [ 0  0  1  4  0]
 [ 1  0  1  0 19]]
akurasi latih:  100.0
akurasi uji:  88.24

9
Empty DataFrame
Columns: [Jenis, Luas_Inti, Keliling_Inti, Solidity_Inti, Granularity_Inti, Circularity_Inti, RerataR_Inti, RerataG_Inti, RerataB_Inti, Entropi_Inti, Energi_Inti, Kontras_Inti, Homogenitas_Inti, LuasP, KelilingP, SolidityP, GranularityP, CircularityP, RerataRP, RerataGP, RerataBP, EntropiP, EnergiP, KontrasP, HomogenitasP, LuasNormal_P, KelilingNormal_I, Eccentricity]
Index: []

[0 rows x 28 columns]
MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=28, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_star

In [6]:
train

[100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]

In [7]:
cv_score

[93.35,
 93.53,
 91.75,
 91.82000000000001,
 93.46,
 92.62,
 93.53,
 91.82000000000001,
 94.22,
 93.42]

In [8]:
test

[94.12, 90.2, 84.31, 90.2, 86.27, 92.16, 82.35, 86.27, 88.24, 86.27]

In [ ]:
'''#adam finish
k2 = ['Jenis','Granularity_Inti','GranularityP']
k1 =['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti']
k7 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP']
k8 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
k4 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti']
k10 =['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP']
k9 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP','LuasNormal_P','KelilingNormal_I']
k6 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP','LuasNormal_P','KelilingNormal_I','LuasP','KelilingP']
k3 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP','LuasNormal_P','KelilingNormal_I','LuasP','KelilingP','Circularity_Inti','CircularityP','Eccentricity']
k5 = ['Jenis','Granularity_Inti','GranularityP', 'Luas_Inti','Keliling_Inti','RerataRP','RerataGP','RerataBP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','RerataR_Inti','RerataG_Inti','RerataB_Inti', 'LIperLP ','KIperKP','LuasNormal_P','KelilingNormal_I','LuasP','KelilingP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti']

datset = [k2, k1, k7, k8, k4, k10, k9, k6, k3, k5]'''

In [ ]:

k7 = ['Jenis','RerataRP','RerataGP','RerataBP']
k3 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity']
k5 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti']
k10 =['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP']
k8 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
k9 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','LuasNormal_P','KelilingNormal_I']
k4 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','LuasNormal_P','KelilingNormal_I','RerataR_Inti','RerataG_Inti','RerataB_Inti']
k2 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','LuasNormal_P','KelilingNormal_I','RerataR_Inti','RerataG_Inti','RerataB_Inti','Granularity_Inti','GranularityP']
k6 = ['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','LuasNormal_P','KelilingNormal_I','RerataR_Inti','RerataG_Inti','RerataB_Inti','Granularity_Inti','GranularityP','LuasP','KelilingP']
k1 =['Jenis','RerataRP','RerataGP','RerataBP','Circularity_Inti','CircularityP','Eccentricity','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti', 'LIperLP ','KIperKP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP','LuasNormal_P','KelilingNormal_I','RerataR_Inti','RerataG_Inti','RerataB_Inti','Granularity_Inti','GranularityP','LuasP','KelilingP', 'Luas_Inti','Keliling_Inti']

datset = [k7,k3,k5,k10,k8,k9,k4,k2,k6,k1]

In [ ]:
# Latih kecerdasan buatan dengan data latih, menggunakan MLP-NN
df = pd.read_excel('Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0, sheet_name ='Data Fitur Citra Sel Darah2')
df = df.drop(datset[0], axis=1)
#df = df[datset[6]]
print(df[0:0])

import numpy as np
y= np.array(df)[:,0]           #membuat dataset target y
X = np.array(df)[:,1:30]    #membuat dataset input X

# Pisahkan dataset menjadi data latih dan uji dengan perbandingan 80:20
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=0)

# Penyekalaan fitur dilakukan pada data latih dan uji.
# Detail kenapa ini penting dijelaskan di sini: http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

# Fungsi fit_transform hanya dilakukan di data latih
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


from sklearn.neural_network import MLPClassifier

i=10
data = [ ]
layers = [ ]
loss = [ ]
iterasi = [ ]
cv_score = [ ]
std_cv = [ ]
while (i<75):
    clf = MLPClassifier(activation='tanh',solver='adam', alpha=1e-5, max_iter=2000,
                    hidden_layer_sizes=(i), random_state=1)
    print(clf.fit(X_train, y_train))
    if(i>=30):
        i=i+5
    elif(i<30):  
        i=i+1

    print('Loss Pelatihan : ', clf.loss_)    
    print('Jumlah iterasi : ', clf.n_iter_)
    
    from sklearn.model_selection import cross_val_score
    scoring='accuracy'
    accuracies = cross_val_score(estimator=clf, X=X_train, y=y_train, cv=5,scoring=scoring)
    avg_accuracy = float('{0:.4f}'.format(accuracies.mean()))*100
    std_accuracy =  float('{0:.4f}'.format(accuracies.std()))*100
    print('Akurasi: ', avg_accuracy)
    print('SD: ', std_accuracy)
    
    #Prediksi Data Uji
    result = clf.predict(X_test)

    #Confusion Matriks Hasil Prediksi dengan Nilai Sebenarnya
    from sklearn.metrics import classification_report,confusion_matrix
    print(confusion_matrix(y_test,result))

    # Cek kemampuan kecerdasan buatan dengan data uji 
    test_accuracy = clf.score(X_test, y_test)
    from sklearn.metrics import accuracy_score
    akurasi = accuracy_score(y_test, result)
    print('Akurasi Data Uji:', test_accuracy , '=', akurasi)

    # Cek kemampuan kecerdasan buatan dengan data uji 
    train_accuracy = clf.score(X_train, y_train)
    print('Akurasi Data Latih:', train_accuracy)  

    layers.append(i)
    data.append( float('{0:.4f}'.format(test_accuracy))*100)
    loss.append(clf.loss_)
    iterasi.append(clf.n_iter_)
    cv_score.append(avg_accuracy)
    std_cv.append(std_accuracy)
    print()

In [ ]:
data

In [ ]:
import pandas as pd
summary = [ ]
i=0
while(i<len(layers)):
    summary.append([layers[i],data[i],loss[i], iterasi[i], cv_score[i],std_cv[i]]) 
    i+=1
    
df = pd.DataFrame(np.array(summary))
df.columns = (['neuron','akurasi','loss','iter','cv','std'])
df

In [ ]:
print(len(layers))
print(layers[10],data[9],loss[9], iterasi[9], cv_score[9],std_cv[9])
i=0
while(i<len(layers)):
    print([layers[i],data[i],loss[i], iterasi[i], cv_score[i],std_cv[i]]) 
    i+=1

In [ ]:
df = pd.read_excel('Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0,sheet_name='Data Fitur Citra Sel Darah2')
df = df.drop(datset[0], axis=1)
#df = df[Jenis, k1]
print(df[0:0])

import numpy as np
y= np.array(df)[:,0]           #membuat dataset target y
X = np.array(df)[:,1:30]    #membuat dataset input X

# Pisahkan dataset menjadi data latih dan uji dengan perbandingan 80:20
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=0)

# Penyekalaan fitur dilakukan pada data latih dan uji.
# Detail kenapa ini penting dijelaskan di sini: http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

# Fungsi fit_transform hanya dilakukan di data latih
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

 # Latih kecerdasan buatan dengan data latih, menggunakan MLP-NN
from sklearn.neural_network import MLPClassifier
import time

clf = MLPClassifier(activation='tanh',solver='adam', alpha=1e-5, max_iter=2000,
            hidden_layer_sizes=(28), random_state=1)
start = time.time()
print(clf.fit(X_train, y_train))
end = time.time()
waktuTrain = end - start
'''
from sklearn.model_selection import cross_val_score
scoring='accuracy'
accuracies = cross_val_score(estimator=clf, X=X_train, y=y_train, cv=10,scoring=scoring)
avg_accuracy = float('{0:.4f}'.format(accuracies.mean()))*100
std_accuracy =  float('{0:.4f}'.format(accuracies.std()))*100
print('Akurasi: ', avg_accuracy)
print('SD: ', std_accuracy)
'''

#prediksi
start = time.time()
result = clf.predict(X_test)
end = time.time()
waktuTest = end - start

#Confusion Matriks Hasil Prediksi dengan Nilai Sebenarnya
from sklearn.metrics import classification_report,confusion_matrix, roc_auc_score
print(confusion_matrix(y_test,result))

# Cek kemampuan kecerdasan buatan dengan data uji 
train_accuracy = float('{0:.4f}'.format(clf.score(X_train, y_train)))*100
print("akurasi latih: ",train_accuracy)

# Cek kemampuan kecerdasan buatan dengan data uji 
test_accuracy = float('{0:.4f}'.format(clf.score(X_test, y_test)))*100
print("akurasi uji: ",test_accuracy)


print()

# Compute confusion matrix
cnf_matrix = confusion_matrix(y_test, result)
np.set_printoptions(precision=2)

class_names = ['Basofil', 'Eosinofil','Netrofil','Monosit','Limfosit']


# Plot non-normalized confusion matrix
plt.figure()
plot_confusion_matrix(cnf_matrix, classes=class_names,
                      title='Confusion matrix')

from sklearn.metrics import classification_report,confusion_matrix, roc_auc_score
print(classification_report(y_test,result, target_names=['basofil','eosinofil','netrofil','monosit', 'limfosit']))

In [ ]:
import itertools
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')