In [1]:
import pandas as pd
import numpy as np
#df = pd.read_excel('Urut-Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0)
df = pd.read_excel('Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0,sheet_name='Data Fitur Citra Sel Darah2')

In [13]:
head = ['Jenis', 'KIperKP', 'KontrasP', 'Solidity_Inti', 'HomogenitasP',
        'Circularity_Inti', 'Keliling_Inti', 'LIperLP ', 'KelilingP',
        'EntropiP', 'LuasNormal_P', 'EnergiP', 'Homogenitas_Inti',
        'KelilingNormal_I', 'Entropi_Inti', 'Granularity_Inti',
        'RerataGP', 'SolidityP', 'Energi_Inti', 'RerataRP',
        'RerataR_Inti', 'CircularityP', 'LuasP', 'GranularityP',
        'RerataG_Inti', 'RerataBP', 'Eccentricity', 'RerataB_Inti',
        'Kontras_Inti', 'Luas_Inti']

In [14]:
k1 =[ 'Luas_Inti','Keliling_Inti']
k2 = ['Granularity_Inti','GranularityP']
k3 = ['Circularity_Inti','CircularityP','Eccentricity']
k4 = ['RerataR_Inti','RerataG_Inti','RerataB_Inti']
k5 = ['Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti']
k6 = ['LuasP','KelilingP']
k7 = ['RerataRP','RerataGP','RerataBP']
k8 = ['SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
k9 = ['LuasNormal_P','KelilingNormal_I']
k10 =[ 'LIperLP ','KIperKP']

datset = [k1,k2,k3,k4,k5,k6,k7,k8,k9,k10]

#adam
#    1          2         3         4         5          6          7          8           9         10
#[99.15, 99.15, 99.15, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 99.15]
#[88.24, 86.27, 86.27, 88.24, 86.27, 88.24, 88.24, 82.35, 84.31, 86.27]

#lbfgs
#    1          2         3         4         5          6          7          8           9         10
#[100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
#[90.2, 84.31, 82.35, 86.27, 90.2, 88.24, 86.27, 80.39, 88.24, 80.39]

In [15]:
tolen= 0
for i in range(len(datset)):
    tolen = tolen +len(datset[i])
print(tolen)
len(datset)

29


10

In [1]:
#lbfgs finish
k2 = ['Jenis','Granularity_Inti','GranularityP']
k8 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
k10 =['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP']
k7 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP']
k4 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti']
k9 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I']
k3 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity']
k1 = [ 'Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity','Luas_Inti','Keliling_Inti']
k6 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity','Luas_Inti','Keliling_Inti','LuasP','KelilingP']
k5 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity','Luas_Inti','Keliling_Inti','LuasP','KelilingP','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti']

datset = [k2, k8, k10, k7, k4, k9, k3, k1, k6, k5]

In [ ]:
#Reordering Columns by name
df = pd.read_excel('Urut-Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0)
df = df[k2]
#df

In [16]:
y

array([22333, 31025, 36832, 34974, 31828, 23701, 31947, 28686, 28145,
       26639, 54900, 37200, 35263, 24821, 32936, 27179, 28187, 40821,
       30883, 28100, 35217, 35026, 25218, 41732, 29861, 28558, 30928,
       27450, 28391, 23243, 35642, 34159, 26744, 35215, 24559, 25111,
       29645, 34941, 29239, 31878, 29096, 46363, 38425, 38508, 29013,
       20039, 39126, 33502, 29962, 31247, 35741, 48805, 46334, 44978,
       43862, 53046, 43184, 31470, 45508, 48103, 51359, 40934, 53864,
       52353, 52080, 50335, 50442, 48755, 47642, 47233, 52077, 21508,
       24217, 22615, 23241, 26865, 23915, 26241, 29848, 21213, 26120,
       23583, 30839, 28876, 37029, 27191, 27971, 34446, 40094, 37051,
       47121, 38332, 30701, 33049, 22332, 35618, 25826, 38926, 21003,
       44015, 37634, 40912, 41935, 51278, 52381, 26609, 24340, 24398,
       26219, 23057, 23964, 23342, 21365, 27013, 32231, 18785, 21873,
       27453, 17420, 20281, 38943, 17616, 24379, 28643, 26880, 28772,
       28557, 22772,

In [ ]:
daf = pd.read_excel('Urut-Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0)
#df = daf.drop(datset[0], axis=1)
print(df[0:0])

In [4]:
import itertools
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

In [18]:
train = [ ]
test = [ ]
cv_score = [ ]
cv_std = [ ]
for i in range(10):
    print(i)
    import pandas as pd
    daf = pd.read_excel('Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0, sheet_name ='Data Fitur Citra Sel Darah2')
    df = daf.drop(datset[i], axis=1)
    #df = daf[datset[i]]
    print(df[0:0])

    import numpy as np
    y= np.array(df)[:,0]           #membuat dataset target y
    X = np.array(df)[:,1:30]    #membuat dataset input X

    # Pisahkan dataset menjadi data latih dan uji dengan perbandingan 80:20
    from sklearn.cross_validation import train_test_split
    X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=0)

    # Penyekalaan fitur dilakukan pada data latih dan uji.
    # Detail kenapa ini penting dijelaskan di sini: http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()

    # Fungsi fit_transform hanya dilakukan di data latih
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)

    # Latih kecerdasan buatan dengan data latih, menggunakan MLP-NN
    from sklearn.neural_network import MLPClassifier
    import time

    clf = MLPClassifier(activation='relu',solver='lbfgs', alpha=1e-5, max_iter=2000,
                hidden_layer_sizes=(16), random_state=1)
    start = time.time()
    print(clf.fit(X_train, y_train))
    end = time.time()
    waktuTrain = end - start

    from sklearn.model_selection import cross_val_score
    scoring='accuracy'
    accuracies = cross_val_score(estimator=clf, X=X_train, y=y_train, cv=5,scoring=scoring)
    avg_accuracy = float('{0:.4f}'.format(accuracies.mean()))*100
    std_accuracy =  float('{0:.4f}'.format(accuracies.std()))*100
    print('Akurasi: ', avg_accuracy)
    print('SD: ', std_accuracy)

    #prediksi
    start = time.time()
    result = clf.predict(X_test)
    end = time.time()
    waktuTest = end - start

    #Confusion Matriks Hasil Prediksi dengan Nilai Sebenarnya
    from sklearn.metrics import classification_report,confusion_matrix, roc_auc_score
    print(confusion_matrix(y_test,result))

    # Cek kemampuan kecerdasan buatan dengan data uji 
    train_accuracy = float('{0:.4f}'.format(clf.score(X_train, y_train)))*100
    print("akurasi latih: ",train_accuracy)

    # Cek kemampuan kecerdasan buatan dengan data uji 
    test_accuracy = float('{0:.4f}'.format(clf.score(X_test, y_test)))*100
    print("akurasi uji: ",test_accuracy)

    train.append(train_accuracy)
    cv_score.append(avg_accuracy)
    cv_std.append(std_accuracy)
    test.append(test_accuracy)
    print()
    


0
Empty DataFrame
Columns: [Jenis, Solidity_Inti, Granularity_Inti, Circularity_Inti, RerataR_Inti, RerataG_Inti, RerataB_Inti, Entropi_Inti, Energi_Inti, Kontras_Inti, Homogenitas_Inti, LuasP, KelilingP, SolidityP, GranularityP, CircularityP, RerataRP, RerataGP, RerataBP, EntropiP, EnergiP, KontrasP, HomogenitasP, LuasNormal_P, KelilingNormal_I, Eccentricity, LIperLP , KIperKP]
Index: []

[0 rows x 28 columns]
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=16, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Akurasi:  91.75
SD:  6.04
[[ 9  1  0  0  1]
 [ 1  0  1  0  0]
 [ 0  0 11  0  1]
 [ 0  1  1  3  0]
 [ 0  0  2  0 19]]
akurasi latih:  100.0
akurasi uji:  82.3

Empty DataFrame
Columns: [Jenis, Luas_Inti, Keliling_Inti, Solidity_Inti, Granularity_Inti, Circularity_Inti, RerataR_Inti, RerataG_Inti, RerataB_Inti, Entropi_Inti, Energi_Inti, Kontras_Inti, Homogenitas_Inti, LuasP, KelilingP, SolidityP, GranularityP, CircularityP, RerataRP, RerataGP, RerataBP, EntropiP, EnergiP, KontrasP, HomogenitasP, LuasNormal_P, KelilingNormal_I, Eccentricity]
Index: []

[0 rows x 28 columns]
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=16, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Akurasi:  93.42
SD:  6.92
[[ 8  3  0  0  0]
 [ 1  0  1  0  0]
 [ 0  0 10  1  1]
 [ 0  2  0  3  0]
 [ 1  0  1  0 19]]
akurasi latih:  100.0
akurasi uji: 

In [ ]:
train

In [ ]:
cv_score

In [ ]:
cv_std

In [ ]:
test

In [20]:
#lbfgs finish
k2 = ['Jenis','Granularity_Inti','GranularityP']
k8 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP']
k10 =['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP']
k7 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP']
k4 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti']
k9 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I']
k3 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity']
k1 =[ 'Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity','Luas_Inti','Keliling_Inti']
k6 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity','Luas_Inti','Keliling_Inti','LuasP','KelilingP']
k5 = ['Jenis','Granularity_Inti','GranularityP','SolidityP','EntropiP','EnergiP','KontrasP','HomogenitasP', 'LIperLP ','KIperKP','RerataRP','RerataGP','RerataBP','RerataR_Inti','RerataG_Inti','RerataB_Inti','LuasNormal_P','KelilingNormal_I','Circularity_Inti','CircularityP','Eccentricity','Luas_Inti','Keliling_Inti','LuasP','KelilingP','Solidity_Inti','Entropi_Inti','Energi_Inti','Kontras_Inti','Homogenitas_Inti']

datset = [k2, k8, k10, k7, k4, k9, k3, k1, k6, k5]

In [2]:
# Latih kecerdasan buatan dengan data latih, menggunakan MLP-NN
import pandas as pd
df = pd.read_excel('Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0, sheet_name ='Data Fitur Citra Sel Darah2')
#df = daf.drop(datset[i], axis=1)
df = df[datset[4]]
print(df[0:0])

import numpy as np
y= np.array(df)[:,0]           #membuat dataset target y
X = np.array(df)[:,1:30]    #membuat dataset input X

# Pisahkan dataset menjadi data latih dan uji dengan perbandingan 80:20
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=0)

# Penyekalaan fitur dilakukan pada data latih dan uji.
# Detail kenapa ini penting dijelaskan di sini: http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

# Fungsi fit_transform hanya dilakukan di data latih
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.neural_network import MLPClassifier

i=10
data = [ ]
layers = [ ]
loss = [ ]
iterasi = [ ]
cv_score = [ ]
std_cv = [ ]
while (i<75):
    clf = MLPClassifier(activation='relu',solver='lbfgs', alpha=1e-5, max_iter=2000,
                    hidden_layer_sizes=(i), random_state=1)
    print(clf.fit(X_train, y_train))
    if(i>=30):
        i=i+5
    elif(i<30):  
        i=i+1

    print('Loss Pelatihan : ', clf.loss_)    
    print('Jumlah iterasi : ', clf.n_iter_)
    
    from sklearn.model_selection import cross_val_score
    scoring='accuracy'
    accuracies = cross_val_score(estimator=clf, X=X_train, y=y_train, cv=5,scoring=scoring)
    avg_accuracy = float('{0:.4f}'.format(accuracies.mean()))*100
    std_accuracy =  float('{0:.4f}'.format(accuracies.std()))*100
    print('Akurasi: ', avg_accuracy)
    print('SD: ', std_accuracy)
    
    #Prediksi Data Uji
    result = clf.predict(X_test)

    #Confusion Matriks Hasil Prediksi dengan Nilai Sebenarnya
    from sklearn.metrics import classification_report,confusion_matrix
    print(confusion_matrix(y_test,result))

    # Cek kemampuan kecerdasan buatan dengan data uji 
    test_accuracy = clf.score(X_test, y_test)
    from sklearn.metrics import accuracy_score
    akurasi = accuracy_score(y_test, result)
    print('Akurasi Data Uji:', test_accuracy , '=', akurasi)

    # Cek kemampuan kecerdasan buatan dengan data uji 
    train_accuracy = clf.score(X_train, y_train)
    print('Akurasi Data Latih:', train_accuracy)  

    layers.append(i)
    data.append( float('{0:.4f}'.format(test_accuracy))*100)
    loss.append(clf.loss_)
    iterasi.append(clf.n_iter_)
    cv_score.append(avg_accuracy)
    std_cv.append(std_accuracy)
    print()
    
    

Empty DataFrame
Columns: [Jenis, Granularity_Inti, GranularityP, SolidityP, EntropiP, EnergiP, KontrasP, HomogenitasP, LIperLP , KIperKP, RerataRP, RerataGP, RerataBP, RerataR_Inti, RerataG_Inti, RerataB_Inti]
Index: []


D:\ProgramFiles\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=10, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  8.69554580262e-05
Jumlah iterasi :  30
Akurasi:  88.37
SD:  8.36
[[11  0  0  0  0]
 [ 1  1  0  0  0]
 [ 0  0 10  0  2]
 [ 0  0  0  5  0]
 [ 1  0  1  0 19]]
Akurasi Data Uji: 0.901960784314 = 0.901960784314
Akurasi Data Latih: 1.0

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=11, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=T

Akurasi:  87.47
SD:  6.58
[[11  0  0  0  0]
 [ 1  1  0  0  0]
 [ 0  0 11  0  1]
 [ 1  0  0  4  0]
 [ 1  0  1  0 19]]
Akurasi Data Uji: 0.901960784314 = 0.901960784314
Akurasi Data Latih: 1.0

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=25, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  8.58342460209e-05
Jumlah iterasi :  24
Akurasi:  90.99000000000001
SD:  8.110000000000001
[[11  0  0  0  0]
 [ 0  2  0  0  0]
 [ 0  0 11  0  1]
 [ 1  0  0  4  0]
 [ 1  0  1  0 19]]
Akurasi Data Uji: 0.921568627451 = 0.921568627451
Akurasi Data Latih: 1.0

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_st

Akurasi:  86.63
SD:  8.469999999999999
[[11  0  0  0  0]
 [ 1  1  0  0  0]
 [ 0  0 10  0  2]
 [ 0  0  1  4  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.901960784314 = 0.901960784314
Akurasi Data Latih: 1.0

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=65, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Loss Pelatihan :  0.000115484135106
Jumlah iterasi :  23
Akurasi:  88.44999999999999
SD:  9.24
[[11  0  0  0  0]
 [ 1  1  0  0  0]
 [ 0  0 10  0  2]
 [ 0  0  0  5  0]
 [ 0  0  1  0 20]]
Akurasi Data Uji: 0.921568627451 = 0.921568627451
Akurasi Data Latih: 1.0

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_st

In [ ]:
data

In [3]:
import pandas as pd
summary = [ ]
i=0
while(i<len(layers)):
    summary.append([layers[i],data[i],loss[i], iterasi[i], cv_score[i],std_cv[i]]) 
    i+=1
    
df = pd.DataFrame(np.array(summary))
df.columns = (['neuron','akurasi','loss','iter','cv','std'])
df

neuron  akurasi      loss  iter     cv   std
0     11.0    90.20  0.000087  30.0  88.37  8.36
1     12.0    88.24  0.000049  21.0  87.43  7.13
2     13.0    90.20  0.000043  25.0  87.50  7.76
3     14.0    88.24  0.000065  23.0  84.82  8.33
4     15.0    94.12  0.000089  33.0  89.24  8.83
5     16.0    94.12  0.000069  27.0  85.76  7.69
6     17.0    94.12  0.000087  24.0  88.38  9.56
7     18.0    92.16  0.000069  21.0  87.58  9.14
8     19.0    90.20  0.000057  26.0  85.76  7.18
9     20.0    92.16  0.000108  21.0  88.37  8.36
10    21.0    92.16  0.000060  26.0  89.25  7.85
11    22.0    92.16  0.000040  26.0  86.63  7.53
12    23.0    90.20  0.000064  25.0  88.37  8.36
13    24.0    92.16  0.000056  21.0  88.41  8.79
14    25.0    90.20  0.000058  22.0  87.47  6.58
15    26.0    92.16  0.000086  24.0  90.99  8.11
16    27.0    90.20  0.000052  22.0  89.17  6.80
17    28.0    88.24  0.000057  23.0  88.41  8.35
18    29.0    92.16  0.000089  21.0  88.34  6.74
19    30.0    90.20  0.000053  23.0  90.08  7.26
20    35.0    92.16  0.000052  24.0  89.32  9.26
21    40.0    92.16  0.000084  21.0  88.34  6.74
22    45.0    90.20  0.000068  21.0  90.99  8.11
23    50.0    90.20  0.000041  23.0  89.24  9.25
24    55.0    88.24  0.000053  22.0  89.32  9.66
25    60.0    92.16  0.000064  20.0  88.38  9.56
26    65.0    90.20  0.000184  18.0  86.63  8.47
27    70.0    92.16  0.000115  23.0  88.45  9.24
28    75.0    94.12  0.000081  23.0  88.37  8.36

In [5]:
df = pd.read_excel('Data-20Fitur-20Citra-20Sel-20Darah.xlsx', header=0,sheet_name='Data Fitur Citra Sel Darah2')
#df = daf.drop(datset[i], axis=1)
df = df[datset[4]]
print(df[0:0])

import numpy as np
y= np.array(df)[:,0]           #membuat dataset target y
X = np.array(df)[:,1:30]    #membuat dataset input X

# Pisahkan dataset menjadi data latih dan uji dengan perbandingan 80:20
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30, random_state=0)

# Penyekalaan fitur dilakukan pada data latih dan uji.
# Detail kenapa ini penting dijelaskan di sini: http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

# Fungsi fit_transform hanya dilakukan di data latih
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

 # Latih kecerdasan buatan dengan data latih, menggunakan MLP-NN
from sklearn.neural_network import MLPClassifier
import time

clf = MLPClassifier(activation='relu',solver='lbfgs', alpha=1e-5, max_iter=2000,
            hidden_layer_sizes=(14), random_state=1)
start = time.time()
print(clf.fit(X_train, y_train))
end = time.time()
waktuTrain = end - start

from sklearn.model_selection import cross_val_score
scoring='accuracy'
accuracies = cross_val_score(estimator=clf, X=X_train, y=y_train, cv=5,scoring=scoring)
avg_accuracy = float('{0:.4f}'.format(accuracies.mean()))*100
std_accuracy =  float('{0:.4f}'.format(accuracies.std()))*100
print('Akurasi cv: ', avg_accuracy)
print('SD: ', std_accuracy)

#prediksi
start = time.time()
result = clf.predict(X_test)
end = time.time()
waktuTest = end - start

#Confusion Matriks Hasil Prediksi dengan Nilai Sebenarnya
from sklearn.metrics import classification_report,confusion_matrix, roc_auc_score
print(confusion_matrix(y_test,result))

# Cek kemampuan kecerdasan buatan dengan data uji 
train_accuracy = float('{0:.4f}'.format(clf.score(X_train, y_train)))*100
print("akurasi latih: ",train_accuracy)

# Cek kemampuan kecerdasan buatan dengan data uji 
test_accuracy = float('{0:.4f}'.format(clf.score(X_test, y_test)))*100
print("akurasi uji: ",test_accuracy)

# Compute confusion matrix
cnf_matrix = confusion_matrix(y_test, result)
np.set_printoptions(precision=2)

class_names = ['Basofil', 'Eosinofil','Netrofil','Monosit','Limfosit']


# Plot non-normalized confusion matrix
plt.figure()
plot_confusion_matrix(cnf_matrix, classes=class_names,
                      title='Confusion matrix')

from sklearn.metrics import classification_report,confusion_matrix, roc_auc_score
print(classification_report(y_test,result, target_names=['basofil','eosinofil','netrofil','monosit', 'limfosit']))

Empty DataFrame
Columns: [Jenis, Granularity_Inti, GranularityP, SolidityP, EntropiP, EnergiP, KontrasP, HomogenitasP, LIperLP , KIperKP, RerataRP, RerataGP, RerataBP, RerataR_Inti, RerataG_Inti, RerataB_Inti]
Index: []
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=14, learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)
Akurasi cv:  89.24
SD:  8.83
[[11  0  0  0  0]
 [ 0  2  0  0  0]
 [ 0  0 10  0  2]
 [ 0  0  0  5  0]
 [ 0  0  1  0 20]]
akurasi latih:  100.0
akurasi uji:  94.12
Confusion matrix, without normalization
[[11  0  0  0  0]
 [ 0  2  0  0  0]
 [ 0  0 10  0  2]
 [ 0  0  0  5  0]
 [ 0  0  1  0 20]]
             precision    recall  f1-score   support

    b

In [13]:
print(result)

[5. 3. 5. 3. 5. 5. 1. 1. 5. 5. 3. 4. 5. 3. 3. 2. 3. 4. 5. 4. 5. 5. 5. 5.
 3. 5. 1. 5. 5. 1. 1. 5. 5. 1. 3. 2. 1. 3. 4. 1. 5. 5. 5. 1. 3. 5. 1. 5.
 1. 3. 4.]


In [14]:
print(y_test)


[5. 3. 5. 3. 5. 3. 1. 1. 3. 5. 3. 4. 5. 5. 3. 2. 3. 4. 5. 4. 5. 5. 5. 5.
 3. 5. 1. 5. 5. 1. 1. 5. 5. 1. 3. 2. 1. 3. 4. 1. 5. 5. 5. 1. 3. 5. 1. 5.
 1. 3. 4.]


In [6]:
#Banyak bobot yang digunakan
print([coef.shape for coef in clf.coefs_])
print("weights between input and first hidden layer:")
print(clf.coefs_[0])
print("\nweights between first hidden and second hidden layer:")
print(clf.coefs_[1])
print("Bias values for first hidden layer:")
print(clf.intercepts_[0])
print("\nBias values for second hidden layer:")
print(clf.intercepts_[1])

[(15, 14), (14, 5)]
weights between input and first hidden layer:
[[-2.92 -2.89 -3.15 -0.36 -2.55 -3.26 -1.4  -2.97 -0.37 -0.61 -6.52  3.24
  -1.35  1.45]
 [-1.59  0.95 -1.69  0.59 -2.28 -0.49 -0.12  0.19  0.81  0.14 -0.78  1.6
  -2.06  1.63]
 [ 0.48 -1.66 -2.41 -0.3   0.49 -2.33  0.1   0.52 -0.66 -0.05 -1.02  2.02
   0.55  2.58]
 [ 0.46  2.64  0.31  0.24 -0.04  0.7   0.18  0.08 -0.56  0.24  1.45  0.41
  -0.57 -0.64]
 [-0.64 -2.53 -0.6  -0.14  0.23 -0.87 -0.21 -0.78 -0.52  0.05 -1.26 -0.97
   0.91 -0.05]
 [ 3.82  0.77 -0.36  0.95 -1.25 -1.09  1.04  0.49 -1.34  0.83 -1.    0.2
  -0.08  0.3 ]
 [-0.66 -2.31 -1.17  0.17  0.29 -1.36 -0.64  0.26  0.41 -0.09 -2.06 -0.71
   0.85  0.64]
 [-0.07 -2.38  0.13 -0.31  1.76 -0.72  0.4   0.41 -1.78  0.87 -0.27 -2.18
   0.29 -1.4 ]
 [-3.12  2.83  1.14  0.62  1.81  4.65 -0.03 -2.99 -0.4  -1.01  0.31  1.24
   0.04 -0.57]
 [ 1.12  1.01 -0.02  0.05 -0.53 -0.24  0.22  0.61  0.41 -0.32  0.5   1.96
  -0.22  0.71]
 [ 2.77 -0.54 -1.29 -0.08 -2.3  -1.8   0.43  2